export type EmojiEntry = {
  emoji: string;
  name: string;
  keywords: string[];
};

// Derived from Unicode CLDR short names + curated keywords (trimmed for bundle size).
export const EMOJI_DATA: EmojiEntry[] = [
  { emoji: "😀", name: "grinning face", keywords: ["smile", "happy", "joy"] },
  { emoji: "😁", name: "beaming face with smiling eyes", keywords: ["smile", "eyes", "happy"] },
  { emoji: "😂", name: "face with tears of joy", keywords: ["lol", "cry", "tears"] },
  { emoji: "🤣", name: "rolling on the floor laughing", keywords: ["rofl", "lol", "laugh"] },
  { emoji: "😃", name: "grinning face with big eyes", keywords: ["smile", "happy", "big"] },
  { emoji: "😄", name: "grinning face with smiling eyes", keywords: ["smile", "happy"] },
  { emoji: "😅", name: "grinning face with sweat", keywords: ["awkward", "relief"] },
  { emoji: "😆", name: "grinning squinting face", keywords: ["xD", "laugh"] },
  { emoji: "😉", name: "winking face", keywords: ["wink", "flirt"] },
  { emoji: "😊", name: "smiling face with smiling eyes", keywords: ["blush", "warm"] },
  { emoji: "😋", name: "face savoring food", keywords: ["yum", "nom", "tongue"] },
  { emoji: "😎", name: "smiling face with sunglasses", keywords: ["cool", "swag"] },
  { emoji: "😍", name: "smiling face with heart-eyes", keywords: ["love", "hearts"] },
  { emoji: "😘", name: "face blowing a kiss", keywords: ["kiss", "love"] },
  { emoji: "😗", name: "kissing face", keywords: ["kiss", "love"] },
  { emoji: "😙", name: "kissing face with smiling eyes", keywords: ["kiss", "love"] },
  { emoji: "😚", name: "kissing face with closed eyes", keywords: ["kiss", "love"] },
  { emoji: "🙂", name: "slightly smiling face", keywords: ["smile", "soft"] },
  { emoji: "🤗", name: "hugging face", keywords: ["hug", "support"] },
  { emoji: "🤩", name: "star-struck", keywords: ["star", "wow"] },
  { emoji: "🥳", name: "partying face", keywords: ["party", "celebrate"] },
  { emoji: "🥰", name: "smiling face with hearts", keywords: ["love", "affection"] },
  { emoji: "😇", name: "smiling face with halo", keywords: ["angel", "innocent"] },
  { emoji: "😐", name: "neutral face", keywords: ["meh", "neutral"] },
  { emoji: "😑", name: "expressionless face", keywords: ["blank", "expressionless"] },
  { emoji: "😶", name: "face without mouth", keywords: ["speechless", "muted"] },
  { emoji: "🙃", name: "upside-down face", keywords: ["sarcasm", "flip"] },
  { emoji: "🫠", name: "melting face", keywords: ["melting", "awkward"] },
  { emoji: "😏", name: "smirking face", keywords: ["smirk", "side-eye"] },
  { emoji: "😒", name: "unamused face", keywords: ["unamused", "meh"] },
  { emoji: "😞", name: "disappointed face", keywords: ["sad", "disappointed"] },
  { emoji: "😔", name: "pensive face", keywords: ["pensive", "sad"] },
  { emoji: "😟", name: "worried face", keywords: ["worried", "concern"] },
  { emoji: "😢", name: "crying face", keywords: ["sad", "cry"] },
  { emoji: "😭", name: "loudly crying face", keywords: ["ugly cry", "sad"] },
  { emoji: "😤", name: "face with steam from nose", keywords: ["triumph", "angry"] },
  { emoji: "😠", name: "angry face", keywords: ["angry", "mad"] },
  { emoji: "😡", name: "pouting face", keywords: ["angry", "pout"] },
  { emoji: "🤬", name: "face with symbols on mouth", keywords: ["cursing", "swear"] },
  { emoji: "🤯", name: "exploding head", keywords: ["mind blown", "shock"] },
  { emoji: "😳", name: "flushed face", keywords: ["embarrassed", "blush"] },
  { emoji: "🥺", name: "pleading face", keywords: ["please", "puppy eyes"] },
  { emoji: "🤡", name: "clown face", keywords: ["clown", "joke"] },
  { emoji: "👻", name: "ghost", keywords: ["spooky", "boo"] },
  { emoji: "💀", name: "skull", keywords: ["dead", "skull"] },
  { emoji: "☠️", name: "skull and crossbones", keywords: ["danger", "poison"] },
  { emoji: "👽", name: "alien", keywords: ["alien", "ufo"] },
  { emoji: "🤖", name: "robot", keywords: ["robot", "bot"] },
  { emoji: "😺", name: "grinning cat", keywords: ["cat", "smile"] },
  { emoji: "😹", name: "cat with tears of joy", keywords: ["cat", "lol"] },
  { emoji: "😻", name: "smiling cat with heart-eyes", keywords: ["cat", "love"] },
  { emoji: "🙈", name: "see-no-evil monkey", keywords: ["monkey", "shy"] },
  { emoji: "🙉", name: "hear-no-evil monkey", keywords: ["monkey", "no hear"] },
  { emoji: "🙊", name: "speak-no-evil monkey", keywords: ["monkey", "secret"] },
  { emoji: "💩", name: "pile of poo", keywords: ["poop", "funny"] },
  { emoji: "💌", name: "love letter", keywords: ["love", "letter"] },
  { emoji: "💘", name: "heart with arrow", keywords: ["heart", "cupid"] },
  { emoji: "💝", name: "heart with ribbon", keywords: ["gift", "love"] },
  { emoji: "💖", name: "sparkling heart", keywords: ["heart", "sparkle"] },
  { emoji: "💗", name: "growing heart", keywords: ["heart", "growing"] },
  { emoji: "💓", name: "beating heart", keywords: ["heart", "beat"] },
  { emoji: "💞", name: "revolving hearts", keywords: ["heart", "revolving"] },
  { emoji: "💕", name: "two hearts", keywords: ["hearts", "love"] },
  { emoji: "💟", name: "heart decoration", keywords: ["heart", "decoration"] },
  { emoji: "❣️", name: "heart exclamation", keywords: ["heart", "exclamation"] },
  { emoji: "💔", name: "broken heart", keywords: ["heart", "broken"] },
  { emoji: "❤️", name: "red heart", keywords: ["heart", "love"] },
  { emoji: "🧡", name: "orange heart", keywords: ["heart", "orange"] },
  { emoji: "💛", name: "yellow heart", keywords: ["heart", "yellow"] },
  { emoji: "💚", name: "green heart", keywords: ["heart", "green"] },
  { emoji: "💙", name: "blue heart", keywords: ["heart", "blue"] },
  { emoji: "💜", name: "purple heart", keywords: ["heart", "purple"] },
  { emoji: "🤎", name: "brown heart", keywords: ["heart", "brown"] },
  { emoji: "🖤", name: "black heart", keywords: ["heart", "black"] },
  { emoji: "🤍", name: "white heart", keywords: ["heart", "white"] },
  { emoji: "💯", name: "hundred points", keywords: ["100", "perfect"] },
  { emoji: "💢", name: "anger symbol", keywords: ["anger", "symbol"] },
  { emoji: "💥", name: "collision", keywords: ["boom", "explosion"] },
  { emoji: "💫", name: "dizzy", keywords: ["sparkle", "dizzy"] },
  { emoji: "💦", name: "sweat droplets", keywords: ["water", "sweat"] },
  { emoji: "💨", name: "dashing away", keywords: ["dash", "fast"] },
  { emoji: "🕳️", name: "hole", keywords: ["hole", "void"] },
  { emoji: "👋", name: "waving hand", keywords: ["hello", "hi", "wave"] },
  { emoji: "🤚", name: "raised back of hand", keywords: ["raise", "hand"] },
  { emoji: "🖐️", name: "hand with fingers splayed", keywords: ["hand", "five"] },
  { emoji: "✋", name: "raised hand", keywords: ["stop", "hand"] },
  { emoji: "🖖", name: "vulcan salute", keywords: ["vulcan", "spock"] },
  { emoji: "👌", name: "OK hand", keywords: ["ok", "perfect"] },
  { emoji: "🤌", name: "pinched fingers", keywords: ["pinch", "chef"] },
  { emoji: "🤏", name: "pinching hand", keywords: ["pinch", "small"] },
  { emoji: "✌️", name: "victory hand", keywords: ["peace", "victory"] },
  { emoji: "🤞", name: "crossed fingers", keywords: ["luck", "fingers"] },
  { emoji: "🤟", name: "love-you gesture", keywords: ["love", "asl"] },
  { emoji: "🤘", name: "sign of the horns", keywords: ["rock", "devil"] },
  { emoji: "🤙", name: "call me hand", keywords: ["call", "shaka"] },
  { emoji: "👈", name: "backhand index pointing left", keywords: ["left", "point"] },
  { emoji: "👉", name: "backhand index pointing right", keywords: ["right", "point"] },
  { emoji: "👆", name: "backhand index pointing up", keywords: ["up", "point"] },
  { emoji: "👇", name: "backhand index pointing down", keywords: ["down", "point"] },
  { emoji: "☝️", name: "index pointing up", keywords: ["up", "point"] },
  { emoji: "👍", name: "thumbs up", keywords: ["like", "approve"] },
  { emoji: "👎", name: "thumbs down", keywords: ["dislike", "down"] },
  { emoji: "✊", name: "raised fist", keywords: ["fist", "power"] },
  { emoji: "👊", name: "oncoming fist", keywords: ["punch", "fist bump"] },
  { emoji: "🤛", name: "left-facing fist", keywords: ["fist", "left"] },
  { emoji: "🤜", name: "right-facing fist", keywords: ["fist", "right"] },
  { emoji: "👏", name: "clapping hands", keywords: ["clap", "applause"] },
  { emoji: "🙌", name: "raising hands", keywords: ["celebrate", "raise"] },
  { emoji: "👐", name: "open hands", keywords: ["open", "hug"] },
  { emoji: "🤲", name: "palms up together", keywords: ["prayer", "cupped"] },
  { emoji: "🙏", name: "folded hands", keywords: ["prayer", "please", "thanks"] },
  { emoji: "✍️", name: "writing hand", keywords: ["write", "hand"] },
  { emoji: "💅", name: "nail polish", keywords: ["nails", "manicure"] },
  { emoji: "🤳", name: "selfie", keywords: ["selfie", "phone"] },
];

export const POPULAR_REACTIONS = ["👍", "❤️", "😂", "😮", "😢", "🙏"];
