/**
 * Registry of semantic design tokens that map to CSS custom properties.
 * This powers Tailwind integration, runtime sanitisation, and AI styling prompts.
 */
export type CSSVariableName = `--${string}`;

export type ThemeTokenCategory =
  | "surface"
  | "text"
  | "border"
  | "brand"
  | "feedback"
  | "typography"
  | "radius"
  | "shadow"
  | "ring"
  | "glass"
  | "card"
  | "dock"
  | "presence"
  | "layout"
  | "spacing"
  | "motion"
  | "utility";

export type ThemeTokenValueKind =
  | "color"
  | "gradient"
  | "shadow"
  | "fontFamily"
  | "radius"
  | "dimension"
  | "time"
  | "timingFunction"
  | "other";

type TailwindGroup =
  | "colors"
  | "borderRadius"
  | "fontFamily"
  | "boxShadow"
  | "backgroundImage"
  | "spacing"
  | "transitionDuration"
  | "transitionTimingFunction";

export interface ThemeTokenDefinition {
  readonly id: string;
  readonly label: string;
  readonly cssVar: CSSVariableName;
  readonly category: ThemeTokenCategory;
  readonly valueKind: ThemeTokenValueKind;
  readonly description?: string;
  readonly tags?: readonly string[];
  readonly tailwind?: {
    readonly path: readonly [TailwindGroup, ...string[]];
  };
}

export const themeTokenRegistry = [
  {
    id: "surface.app",
    label: "Surface / App Base",
    cssVar: "--surface-app",
    category: "surface",
    valueKind: "color",
    tags: ["background", "app"],
    tailwind: {
      path: ["colors", "background"],
    },
  },
  {
    id: "home.railtab.accent-color",
    label: "Home / Rail Tab Accent",
    cssVar: "--home-railtab-accent",
    category: "brand",
    valueKind: "color",
    tags: ["home", "rail", "tab", "accent"],
  },
  {
    id: "surface.muted",
    label: "Surface / Muted Panel",
    cssVar: "--surface-muted",
    category: "surface",
    valueKind: "color",
    tags: ["panel", "muted"],
    tailwind: {
      path: ["colors", "surface", "muted"],
    },
  },
  {
    id: "surface.elevated",
    label: "Surface / Elevated Panel",
    cssVar: "--surface-elevated",
    category: "surface",
    valueKind: "color",
    tags: ["panel", "elevated"],
    tailwind: {
      path: ["colors", "surface", "elevated"],
    },
  },
  {
    id: "surface.overlay",
    label: "Surface / Overlay",
    cssVar: "--surface-overlay",
    category: "surface",
    valueKind: "color",
    tags: ["overlay", "scrim"],
    tailwind: {
      path: ["colors", "surface", "overlay"],
    },
  },
  {
    id: "surface.app-fallback",
    label: "Surface / App Fallback",
    cssVar: "--app-bg",
    category: "surface",
    valueKind: "gradient",
    tags: ["background", "fallback"],
  },
  {
    id: "text.default",
    label: "Text / Default",
    cssVar: "--color-fg",
    category: "text",
    valueKind: "color",
    tags: ["text", "primary"],
    tailwind: {
      path: ["colors", "fg", "DEFAULT"],
    },
  },
  {
    id: "text.muted",
    label: "Text / Muted",
    cssVar: "--color-fg-muted",
    category: "text",
    valueKind: "color",
    tags: ["text", "muted"],
    tailwind: {
      path: ["colors", "fg", "muted"],
    },
  },
  {
    id: "text.subtle",
    label: "Text / Subtle",
    cssVar: "--color-fg-subtle",
    category: "text",
    valueKind: "color",
    tags: ["text", "subtle"],
    tailwind: {
      path: ["colors", "fg", "subtle"],
    },
  },
  {
    id: "text.on-brand",
    label: "Text / On Brand",
    cssVar: "--text-on-brand",
    category: "text",
    valueKind: "color",
    tags: ["text", "brand", "contrast"],
  },
  {
    id: "border.default",
    label: "Border / Default",
    cssVar: "--color-border",
    category: "border",
    valueKind: "color",
    tags: ["border", "divider"],
    tailwind: {
      path: ["colors", "border", "DEFAULT"],
    },
  },
  {
    id: "border.strong",
    label: "Border / Strong",
    cssVar: "--color-border-strong",
    category: "border",
    valueKind: "color",
    tags: ["border", "strong"],
    tailwind: {
      path: ["colors", "border", "strong"],
    },
  },
  {
    id: "brand.primary",
    label: "Brand / Primary",
    cssVar: "--color-brand",
    category: "brand",
    valueKind: "color",
    tags: ["brand", "accent"],
    tailwind: {
      path: ["colors", "brand", "DEFAULT"],
    },
  },
  {
    id: "brand.strong",
    label: "Brand / Strong",
    cssVar: "--color-brand-strong",
    category: "brand",
    valueKind: "color",
    tags: ["brand", "emphasis"],
    tailwind: {
      path: ["colors", "brand", "strong"],
    },
  },
  {
    id: "brand.foreground",
    label: "Brand / Foreground",
    cssVar: "--color-brand-foreground",
    category: "brand",
    valueKind: "color",
    tags: ["brand", "contrast"],
    tailwind: {
      path: ["colors", "brand", "foreground"],
    },
  },
  {
    id: "brand.muted",
    label: "Brand / Muted",
    cssVar: "--color-brand-muted",
    category: "brand",
    valueKind: "color",
    tags: ["brand", "muted"],
    tailwind: {
      path: ["colors", "brand", "muted"],
    },
  },
  {
    id: "brand.gradient",
    label: "Brand / Gradient",
    cssVar: "--gradient-brand",
    category: "brand",
    valueKind: "gradient",
    tags: ["brand", "gradient"],
    tailwind: {
      path: ["backgroundImage", "brand-gradient"],
    },
  },
  {
    id: "brand.cta-gradient",
    label: "Brand / CTA Gradient",
    cssVar: "--cta-gradient",
    category: "brand",
    valueKind: "gradient",
    tags: ["brand", "cta"],
  },
  {
    id: "brand.cta-text",
    label: "Brand / CTA Text",
    cssVar: "--cta-button-text",
    category: "brand",
    valueKind: "color",
    tags: ["brand", "cta", "text"],
  },
  {
    id: "brand.cta-chip-gradient",
    label: "Brand / CTA Chip Gradient",
    cssVar: "--cta-chip-gradient",
    category: "brand",
    valueKind: "gradient",
    tags: ["brand", "cta", "chip", "gradient"],
    tailwind: {
      path: ["backgroundImage", "cta-chip"],
    },
  },
  {
    id: "brand.cta-chip-text",
    label: "Brand / CTA Chip Text",
    cssVar: "--cta-chip-text",
    category: "brand",
    valueKind: "color",
    tags: ["brand", "cta", "chip", "text"],
    tailwind: {
      path: ["colors", "cta", "chipText"],
    },
  },
  {
    id: "brand.accent",
    label: "Brand / Accent",
    cssVar: "--color-accent",
    category: "brand",
    valueKind: "color",
    tags: ["accent", "highlight"],
    tailwind: {
      path: ["colors", "accent"],
    },
  },
  {
    id: "feedback.info",
    label: "Feedback / Info",
    cssVar: "--color-info",
    category: "feedback",
    valueKind: "color",
    tags: ["info", "status"],
    tailwind: {
      path: ["colors", "info"],
    },
  },
  {
    id: "feedback.success",
    label: "Feedback / Success",
    cssVar: "--color-success",
    category: "feedback",
    valueKind: "color",
    tags: ["success", "status"],
    tailwind: {
      path: ["colors", "success"],
    },
  },
  {
    id: "feedback.warning",
    label: "Feedback / Warning",
    cssVar: "--color-warning",
    category: "feedback",
    valueKind: "color",
    tags: ["warning", "status"],
    tailwind: {
      path: ["colors", "warning"],
    },
  },
  {
    id: "feedback.danger",
    label: "Feedback / Danger",
    cssVar: "--color-danger",
    category: "feedback",
    valueKind: "color",
    tags: ["danger", "status"],
    tailwind: {
      path: ["colors", "danger"],
    },
  },
  {
    id: "typography.sans",
    label: "Typography / Sans",
    cssVar: "--font-sans",
    category: "typography",
    valueKind: "fontFamily",
    tags: ["font", "sans"],
    tailwind: {
      path: ["fontFamily", "sans"],
    },
  },
  {
    id: "typography.display",
    label: "Typography / Display",
    cssVar: "--font-display",
    category: "typography",
    valueKind: "fontFamily",
    tags: ["font", "display"],
    tailwind: {
      path: ["fontFamily", "display"],
    },
  },
  {
    id: "typography.mono",
    label: "Typography / Mono",
    cssVar: "--font-mono",
    category: "typography",
    valueKind: "fontFamily",
    tags: ["font", "mono"],
    tailwind: {
      path: ["fontFamily", "mono"],
    },
  },
  {
    id: "radius.xs",
    label: "Radius / XS",
    cssVar: "--radius-xs",
    category: "radius",
    valueKind: "radius",
    tags: ["radius", "xs"],
    tailwind: {
      path: ["borderRadius", "xs"],
    },
  },
  {
    id: "radius.sm",
    label: "Radius / SM",
    cssVar: "--radius-sm",
    category: "radius",
    valueKind: "radius",
    tags: ["radius", "sm"],
    tailwind: {
      path: ["borderRadius", "sm"],
    },
  },
  {
    id: "radius.md",
    label: "Radius / MD",
    cssVar: "--radius-md",
    category: "radius",
    valueKind: "radius",
    tags: ["radius", "md"],
    tailwind: {
      path: ["borderRadius", "md"],
    },
  },
  {
    id: "radius.lg",
    label: "Radius / LG",
    cssVar: "--radius-lg",
    category: "radius",
    valueKind: "radius",
    tags: ["radius", "lg"],
    tailwind: {
      path: ["borderRadius", "lg"],
    },
  },
  {
    id: "radius.xl",
    label: "Radius / XL",
    cssVar: "--radius-xl",
    category: "radius",
    valueKind: "radius",
    tags: ["radius", "xl"],
    tailwind: {
      path: ["borderRadius", "xl"],
    },
  },
  {
    id: "radius.2xl",
    label: "Radius / 2XL",
    cssVar: "--radius-2xl",
    category: "radius",
    valueKind: "radius",
    tags: ["radius", "2xl"],
    tailwind: {
      path: ["borderRadius", "2xl"],
    },
  },
  {
    id: "radius.pill",
    label: "Radius / Pill",
    cssVar: "--radius-pill",
    category: "radius",
    valueKind: "radius",
    tags: ["radius", "pill"],
    tailwind: {
      path: ["borderRadius", "pill"],
    },
  },
  {
    id: "shadow.xs",
    label: "Shadow / XS",
    cssVar: "--shadow-xs",
    category: "shadow",
    valueKind: "shadow",
    tags: ["shadow", "xs"],
    tailwind: {
      path: ["boxShadow", "xs"],
    },
  },
  {
    id: "shadow.sm",
    label: "Shadow / SM",
    cssVar: "--shadow-sm",
    category: "shadow",
    valueKind: "shadow",
    tags: ["shadow", "sm"],
    tailwind: {
      path: ["boxShadow", "sm"],
    },
  },
  {
    id: "shadow.md",
    label: "Shadow / MD",
    cssVar: "--shadow-md",
    category: "shadow",
    valueKind: "shadow",
    tags: ["shadow", "md"],
    tailwind: {
      path: ["boxShadow", "md"],
    },
  },
  {
    id: "shadow.lg",
    label: "Shadow / LG",
    cssVar: "--shadow-lg",
    category: "shadow",
    valueKind: "shadow",
    tags: ["shadow", "lg"],
    tailwind: {
      path: ["boxShadow", "lg"],
    },
  },
  {
    id: "shadow.xl",
    label: "Shadow / XL",
    cssVar: "--shadow-xl",
    category: "shadow",
    valueKind: "shadow",
    tags: ["shadow", "xl"],
    tailwind: {
      path: ["boxShadow", "xl"],
    },
  },
  {
    id: "shadow.glow",
    label: "Shadow / Glow",
    cssVar: "--shadow-glow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["shadow", "glow", "brand"],
    tailwind: {
      path: ["boxShadow", "glow"],
    },
  },
  {
    id: "ring.primary",
    label: "Ring / Primary",
    cssVar: "--ring-primary",
    category: "ring",
    valueKind: "shadow",
    tags: ["ring", "focus"],
  },
  {
    id: "ring.offset",
    label: "Ring / Offset",
    cssVar: "--ring-offset",
    category: "ring",
    valueKind: "shadow",
    tags: ["ring", "offset"],
  },
  {
    id: "glass.bg-1",
    label: "Glass / Background 1",
    cssVar: "--glass-bg-1",
    category: "glass",
    valueKind: "color",
    tags: ["glass", "background"],
  },
  {
    id: "glass.bg-2",
    label: "Glass / Background 2",
    cssVar: "--glass-bg-2",
    category: "glass",
    valueKind: "color",
    tags: ["glass", "background"],
  },
  {
    id: "card.bg-1",
    label: "Card / Background 1",
    cssVar: "--card-bg-1",
    category: "card",
    valueKind: "color",
    tags: ["card", "background"],
  },
  {
    id: "card.bg-2",
    label: "Card / Background 2",
    cssVar: "--card-bg-2",
    category: "card",
    valueKind: "color",
    tags: ["card", "background"],
  },
  {
    id: "card.border",
    label: "Card / Border",
    cssVar: "--card-border",
    category: "card",
    valueKind: "color",
    tags: ["card", "border"],
  },
  {
    id: "dock.bg-1",
    label: "Dock / Background 1",
    cssVar: "--dock-bg-1",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "background"],
  },
  {
    id: "dock.bg-2",
    label: "Dock / Background 2",
    cssVar: "--dock-bg-2",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "background"],
  },
  {
    id: "dock.border",
    label: "Dock / Border",
    cssVar: "--dock-border",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "border"],
  },
  {
    id: "dock.shadow",
    label: "Dock / Shadow",
    cssVar: "--dock-shadow",
    category: "dock",
    valueKind: "shadow",
    tags: ["dock", "shadow"],
  },
  {
    id: "dock.text-muted",
    label: "Dock / Text Muted",
    cssVar: "--dock-text-muted",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "text"],
  },
  {
    id: "dock.btn-bg-1",
    label: "Dock Button / Background 1",
    cssVar: "--dock-btn-bg-1",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "button"],
  },
  {
    id: "dock.btn-bg-2",
    label: "Dock Button / Background 2",
    cssVar: "--dock-btn-bg-2",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "button"],
  },
  {
    id: "dock.btn-border",
    label: "Dock Button / Border",
    cssVar: "--dock-btn-border",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "button", "border"],
  },
  {
    id: "dock.btn-border-hover",
    label: "Dock Button / Border Hover",
    cssVar: "--dock-btn-hover-border",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "button", "hover"],
  },
  {
    id: "dock.active-shadow",
    label: "Dock / Active Shadow",
    cssVar: "--dock-active-shadow",
    category: "dock",
    valueKind: "shadow",
    tags: ["dock", "active"],
  },
  {
    id: "dock.active-glow",
    label: "Dock / Active Glow",
    cssVar: "--dock-active-glow",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "active"],
  },
  {
    id: "dock.sheet-bg-1",
    label: "Dock Sheet / Background 1",
    cssVar: "--dock-sheet-bg-1",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "sheet"],
  },
  {
    id: "dock.sheet-bg-2",
    label: "Dock Sheet / Background 2",
    cssVar: "--dock-sheet-bg-2",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "sheet"],
  },
  {
    id: "dock.sheet-border",
    label: "Dock Sheet / Border",
    cssVar: "--dock-sheet-border",
    category: "dock",
    valueKind: "color",
    tags: ["dock", "sheet", "border"],
  },
  {
    id: "dock.sheet-shadow",
    label: "Dock Sheet / Shadow",
    cssVar: "--dock-sheet-shadow",
    category: "dock",
    valueKind: "shadow",
    tags: ["dock", "sheet", "shadow"],
  },
  {
    id: "presence.online-dot",
    label: "Presence / Online Dot",
    cssVar: "--presence-online-dot",
    category: "presence",
    valueKind: "color",
    tags: ["presence", "online"],
  },
  {
    id: "presence.online-dot-bright",
    label: "Presence / Online Dot Bright",
    cssVar: "--presence-online-dot-bright",
    category: "presence",
    valueKind: "color",
    tags: ["presence", "online", "glow"],
  },
  {
    id: "presence.online-ring",
    label: "Presence / Online Ring",
    cssVar: "--presence-online-ring",
    category: "presence",
    valueKind: "color",
    tags: ["presence", "online"],
  },
  {
    id: "presence.away-dot",
    label: "Presence / Away Dot",
    cssVar: "--presence-away-dot",
    category: "presence",
    valueKind: "color",
    tags: ["presence", "away"],
  },
  {
    id: "presence.away-ring",
    label: "Presence / Away Ring",
    cssVar: "--presence-away-ring",
    category: "presence",
    valueKind: "color",
    tags: ["presence", "away"],
  },
  {
    id: "presence.offline-dot",
    label: "Presence / Offline Dot",
    cssVar: "--presence-offline-dot",
    category: "presence",
    valueKind: "color",
    tags: ["presence", "offline"],
  },
  {
    id: "presence.offline-ring",
    label: "Presence / Offline Ring",
    cssVar: "--presence-offline-ring",
    category: "presence",
    valueKind: "color",
    tags: ["presence", "offline"],
  },
  {
    id: "space.3xs",
    label: "Space / 3XS",
    cssVar: "--space-3xs",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "micro"],
    tailwind: {
      path: ["spacing", "space-3xs"],
    },
  },
  {
    id: "space.2xs",
    label: "Space / 2XS",
    cssVar: "--space-2xs",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "dense"],
    tailwind: {
      path: ["spacing", "space-2xs"],
    },
  },
  {
    id: "space.xs",
    label: "Space / XS",
    cssVar: "--space-xs",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "compact"],
    tailwind: {
      path: ["spacing", "space-xs"],
    },
  },
  {
    id: "space.sm",
    label: "Space / SM",
    cssVar: "--space-sm",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "baseline"],
    tailwind: {
      path: ["spacing", "space-sm"],
    },
  },
  {
    id: "space.sm-plus",
    label: "Space / SM Plus",
    cssVar: "--space-sm-plus",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "baseline"],
    tailwind: {
      path: ["spacing", "space-sm-plus"],
    },
  },
  {
    id: "space.md",
    label: "Space / MD",
    cssVar: "--space-md",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "default"],
    tailwind: {
      path: ["spacing", "space-md"],
    },
  },
  {
    id: "space.md-plus",
    label: "Space / MD Plus",
    cssVar: "--space-md-plus",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "default"],
    tailwind: {
      path: ["spacing", "space-md-plus"],
    },
  },
  {
    id: "space.lg",
    label: "Space / LG",
    cssVar: "--space-lg",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "comfortable"],
    tailwind: {
      path: ["spacing", "space-lg"],
    },
  },
  {
    id: "space.lg-plus",
    label: "Space / LG Plus",
    cssVar: "--space-lg-plus",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "comfortable"],
    tailwind: {
      path: ["spacing", "space-lg-plus"],
    },
  },
  {
    id: "space.xl",
    label: "Space / XL",
    cssVar: "--space-xl",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "roomy"],
    tailwind: {
      path: ["spacing", "space-xl"],
    },
  },
  {
    id: "space.xl-plus",
    label: "Space / XL Plus",
    cssVar: "--space-xl-plus",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "roomy"],
    tailwind: {
      path: ["spacing", "space-xl-plus"],
    },
  },
  {
    id: "space.2xl",
    label: "Space / 2XL",
    cssVar: "--space-2xl",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "section"],
    tailwind: {
      path: ["spacing", "space-2xl"],
    },
  },
  {
    id: "space.3xl",
    label: "Space / 3XL",
    cssVar: "--space-3xl",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "section"],
    tailwind: {
      path: ["spacing", "space-3xl"],
    },
  },
  {
    id: "space.4xl",
    label: "Space / 4XL",
    cssVar: "--space-4xl",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "section"],
    tailwind: {
      path: ["spacing", "space-4xl"],
    },
  },
  {
    id: "space.5xl",
    label: "Space / 5XL",
    cssVar: "--space-5xl",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "section"],
    tailwind: {
      path: ["spacing", "space-5xl"],
    },
  },
  {
    id: "space.6xl",
    label: "Space / 6XL",
    cssVar: "--space-6xl",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "section"],
    tailwind: {
      path: ["spacing", "space-6xl"],
    },
  },
  {
    id: "space.7xl",
    label: "Space / 7XL",
    cssVar: "--space-7xl",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "section"],
    tailwind: {
      path: ["spacing", "space-7xl"],
    },
  },
  {
    id: "space.8xl",
    label: "Space / 8XL",
    cssVar: "--space-8xl",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "hero"],
    tailwind: {
      path: ["spacing", "space-8xl"],
    },
  },
  {
    id: "space.9xl",
    label: "Space / 9XL",
    cssVar: "--space-9xl",
    category: "spacing",
    valueKind: "dimension",
    tags: ["spacing", "hero"],
    tailwind: {
      path: ["spacing", "space-9xl"],
    },
  },
  {
    id: "layout.header-offset",
    label: "Layout / Header Offset",
    cssVar: "--layout-header-offset",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "header", "offset"],
  },
  {
    id: "layout.desktop-bottom-padding",
    label: "Layout / Desktop Bottom Padding",
    cssVar: "--layout-desktop-bottom-padding",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "desktop"],
  },
  {
    id: "layout.page-width-offset",
    label: "Layout / Page Width Offset",
    cssVar: "--layout-page-width-offset",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "desktop"],
  },
  {
    id: "layout.page-gap",
    label: "Layout / Page Gap",
    cssVar: "--layout-page-gap",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "stack"],
  },
  {
    id: "layout.column-gap",
    label: "Layout / Column Gap",
    cssVar: "--layout-column-gap",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "grid"],
  },
  {
    id: "layout.mobile-top-offset",
    label: "Layout / Mobile Top Offset",
    cssVar: "--layout-mobile-top-offset",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "mobile"],
  },
  {
    id: "layout.mobile-bottom-offset",
    label: "Layout / Mobile Bottom Offset",
    cssVar: "--layout-mobile-bottom-offset",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "mobile"],
  },
  {
    id: "layout.mobile-outer-padding-bottom",
    label: "Layout / Mobile Outer Padding Bottom",
    cssVar: "--layout-mobile-outer-padding-bottom",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "mobile"],
  },
  {
    id: "layout.mobile-section-gap",
    label: "Layout / Mobile Section Gap",
    cssVar: "--layout-mobile-section-gap",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "mobile"],
  },
  {
    id: "layout.prompter-margin-bottom",
    label: "Layout / Prompter Margin Bottom",
    cssVar: "--layout-prompter-margin-bottom",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "prompter"],
  },
  {
    id: "layout.prompter-margin-bottom-mobile",
    label: "Layout / Prompter Margin Bottom Mobile",
    cssVar: "--layout-prompter-margin-bottom-mobile",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "prompter", "mobile"],
  },
  {
    id: "layout.dock-gap",
    label: "Layout / Dock Gap",
    cssVar: "--layout-dock-gap",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "dock"],
  },
  {
    id: "layout.dock-padding",
    label: "Layout / Dock Padding",
    cssVar: "--layout-dock-padding",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "dock"],
  },
  {
    id: "layout.dock-bottom-padding",
    label: "Layout / Dock Bottom Padding",
    cssVar: "--layout-dock-bottom-padding",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "dock"],
  },
  {
    id: "layout.dock-sheet-offset",
    label: "Layout / Dock Sheet Offset",
    cssVar: "--layout-dock-sheet-offset",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "dock"],
  },
  {
    id: "layout.dock-sheet-padding",
    label: "Layout / Dock Sheet Padding",
    cssVar: "--layout-dock-sheet-padding",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "dock"],
  },
  {
    id: "layout.mobile-page-gutter",
    label: "Layout / Mobile Page Gutter",
    cssVar: "--mobile-page-gutter",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "spacing", "mobile"],
  },
  {
    id: "layout.mobile-dock-height",
    label: "Layout / Mobile Dock Height",
    cssVar: "--mobile-dock-height",
    category: "layout",
    valueKind: "dimension",
    tags: ["layout", "height", "mobile"],
  },
  {
    id: "motion.duration.quick",
    label: "Motion / Duration Quick",
    cssVar: "--motion-duration-quick",
    category: "motion",
    valueKind: "time",
    tags: ["motion", "duration", "quick"],
    tailwind: {
      path: ["transitionDuration", "quick"],
    },
  },
  {
    id: "motion.duration.medium",
    label: "Motion / Duration Medium",
    cssVar: "--motion-duration-medium",
    category: "motion",
    valueKind: "time",
    tags: ["motion", "duration", "base"],
    tailwind: {
      path: ["transitionDuration", "medium"],
    },
  },
  {
    id: "motion.duration.slow",
    label: "Motion / Duration Slow",
    cssVar: "--motion-duration-slow",
    category: "motion",
    valueKind: "time",
    tags: ["motion", "duration", "slow"],
    tailwind: {
      path: ["transitionDuration", "slow"],
    },
  },
  {
    id: "motion.easing.standard",
    label: "Motion / Easing Standard",
    cssVar: "--motion-ease-standard",
    category: "motion",
    valueKind: "timingFunction",
    tags: ["motion", "easing", "standard"],
    tailwind: {
      path: ["transitionTimingFunction", "standard"],
    },
  },
  {
    id: "motion.easing.emphasized-in",
    label: "Motion / Easing Emphasized In",
    cssVar: "--motion-ease-emphasized-in",
    category: "motion",
    valueKind: "timingFunction",
    tags: ["motion", "easing", "emphasized"],
    tailwind: {
      path: ["transitionTimingFunction", "emphasized-in"],
    },
  },
  {
    id: "motion.easing.emphasized-out",
    label: "Motion / Easing Emphasized Out",
    cssVar: "--motion-ease-emphasized-out",
    category: "motion",
    valueKind: "timingFunction",
    tags: ["motion", "easing", "emphasized"],
    tailwind: {
      path: ["transitionTimingFunction", "emphasized-out"],
    },
  },
  {
    id: "utility.presence-ring-offset",
    label: "Utility / Ring Offset",
    cssVar: "--ring-offset",
    category: "utility",
    valueKind: "shadow",
    tags: ["offset", "ring"],
  },
  {
    id: "brand.accent-glow",
    label: "Brand / Accent Glow",
    cssVar: "--accent-glow",
    category: "brand",
    valueKind: "color",
    tags: ["brand", "glow"],
  },
  {
    id: "feedback.alert.bg",
    label: "Feedback / Alert Background",
    cssVar: "--alert-bg",
    category: "feedback",
    valueKind: "color",
    tags: ["alert", "background"],
  },
  {
    id: "feedback.alert.border",
    label: "Feedback / Alert Border",
    cssVar: "--alert-border",
    category: "feedback",
    valueKind: "color",
    tags: ["alert", "border"],
  },
  {
    id: "feedback.alert.fg",
    label: "Feedback / Alert Foreground",
    cssVar: "--alert-fg",
    category: "feedback",
    valueKind: "color",
    tags: ["alert", "text"],
  },
  {
    id: "feedback.alert.accent",
    label: "Feedback / Alert Accent",
    cssVar: "--alert-accent",
    category: "feedback",
    valueKind: "color",
    tags: ["alert", "accent"],
  },
  {
    id: "utility.header-blur",
    label: "Utility / Header Blur Amount",
    cssVar: "--blur-amount",
    category: "utility",
    valueKind: "dimension",
    tags: ["header", "blur"],
  },
  {
    id: "brand.gradient-alt",
    label: "Brand / Gradient Alt",
    cssVar: "--brand-gradient",
    category: "brand",
    valueKind: "gradient",
    tags: ["brand", "gradient"],
  },
  {
    id: "card.hover-bg-1",
    label: "Card / Hover Background 1",
    cssVar: "--card-hover-bg-1",
    category: "card",
    valueKind: "color",
    tags: ["card", "hover", "background"],
  },
  {
    id: "card.hover-bg-2",
    label: "Card / Hover Background 2",
    cssVar: "--card-hover-bg-2",
    category: "card",
    valueKind: "color",
    tags: ["card", "hover", "background"],
  },
  {
    id: "card.hover-border",
    label: "Card / Hover Border",
    cssVar: "--card-hover-border",
    category: "card",
    valueKind: "color",
    tags: ["card", "hover", "border"],
  },
  {
    id: "card.hover-shadow",
    label: "Card / Hover Shadow",
    cssVar: "--card-hover-shadow",
    category: "card",
    valueKind: "shadow",
    tags: ["card", "hover", "shadow"],
  },
  {
    id: "radius.card",
    label: "Radius / Card",
    cssVar: "--card-radius",
    category: "radius",
    valueKind: "radius",
    tags: ["card", "radius"],
  },
  {
    id: "card.shadow",
    label: "Card / Shadow",
    cssVar: "--card-shadow",
    category: "card",
    valueKind: "shadow",
    tags: ["card", "shadow"],
  },
  {
    id: "layout.create-rows-height",
    label: "Layout / Create Rows Height",
    cssVar: "--create-rows-height",
    category: "layout",
    valueKind: "dimension",
    tags: ["create", "layout"],
  },
  {
    id: "brand.cta-button-gradient",
    label: "Brand / CTA Button Gradient",
    cssVar: "--cta-button-gradient",
    category: "brand",
    valueKind: "gradient",
    tags: ["brand", "cta", "gradient"],
  },
  {
    id: "border.cta-chip",
    label: "Border / CTA Chip",
    cssVar: "--cta-chip-border",
    category: "border",
    valueKind: "color",
    tags: ["cta", "chip", "border"],
  },
  {
    id: "border.cta-chip-hover",
    label: "Border / CTA Chip Hover",
    cssVar: "--cta-chip-border-hover",
    category: "border",
    valueKind: "color",
    tags: ["cta", "chip", "hover", "border"],
  },
  {
    id: "shadow.cta-chip",
    label: "Shadow / CTA Chip",
    cssVar: "--cta-chip-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["cta", "chip", "shadow"],
  },
  {
    id: "shadow.cta-chip-hover",
    label: "Shadow / CTA Chip Hover",
    cssVar: "--cta-chip-shadow-hover",
    category: "shadow",
    valueKind: "shadow",
    tags: ["cta", "chip", "hover", "shadow"],
  },
  {
    id: "radius.cta",
    label: "Radius / CTA",
    cssVar: "--cta-radius",
    category: "radius",
    valueKind: "radius",
    tags: ["cta", "radius"],
  },
  {
    id: "surface.feed-action.bg-1",
    label: "Surface / Feed Action Background 1",
    cssVar: "--feed-action-bg-1",
    category: "surface",
    valueKind: "color",
    tags: ["feed", "action", "background"],
  },
  {
    id: "surface.feed-action.bg-2",
    label: "Surface / Feed Action Background 2",
    cssVar: "--feed-action-bg-2",
    category: "surface",
    valueKind: "color",
    tags: ["feed", "action", "background"],
  },
  {
    id: "surface.feed-action.border",
    label: "Surface / Feed Action Border",
    cssVar: "--feed-action-border",
    category: "surface",
    valueKind: "color",
    tags: ["feed", "action", "border"],
  },
  {
    id: "surface.feed-action.border-hover",
    label: "Surface / Feed Action Border Hover",
    cssVar: "--feed-action-border-hover",
    category: "surface",
    valueKind: "color",
    tags: ["feed", "action", "border", "hover"],
  },
  {
    id: "shadow.feed-action.hover",
    label: "Shadow / Feed Action Hover",
    cssVar: "--feed-action-shadow-hover",
    category: "shadow",
    valueKind: "shadow",
    tags: ["feed", "action", "hover"],
  },
  {
    id: "text.feed.icon",
    label: "Text / Feed Icon",
    cssVar: "--feed-icon-text",
    category: "text",
    valueKind: "color",
    tags: ["feed", "icon", "text"],
    tailwind: {
      path: ["colors", "feed", "icon"],
    },
  },
  {
    id: "brand.header.accent",
    label: "Brand / Header Accent",
    cssVar: "--header-accent",
    category: "brand",
    valueKind: "color",
    tags: ["header", "accent"],
  },
  {
    id: "border.header.base",
    label: "Border / Header Base",
    cssVar: "--header-border-color",
    category: "border",
    valueKind: "color",
    tags: ["header", "border"],
  },
  {
    id: "brand.header.primary",
    label: "Brand / Header Primary",
    cssVar: "--header-brand",
    category: "brand",
    valueKind: "color",
    tags: ["header", "brand"],
  },
  {
    id: "brand.header.strong",
    label: "Brand / Header Strong",
    cssVar: "--header-brand-strong",
    category: "brand",
    valueKind: "color",
    tags: ["header", "brand"],
  },
  {
    id: "surface.header.button-active-bg",
    label: "Surface / Header Button Active Background",
    cssVar: "--header-button-active-bg",
    category: "surface",
    valueKind: "color",
    tags: ["header", "button", "active", "background"],
  },
  {
    id: "border.header.button-active",
    label: "Border / Header Button Active",
    cssVar: "--header-button-active-border",
    category: "border",
    valueKind: "color",
    tags: ["header", "button", "active", "border"],
  },
  {
    id: "shadow.header.button-active",
    label: "Shadow / Header Button Active",
    cssVar: "--header-button-active-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "button", "active", "shadow"],
  },
  {
    id: "surface.header.button-bg",
    label: "Surface / Header Button Background",
    cssVar: "--header-button-bg",
    category: "surface",
    valueKind: "color",
    tags: ["header", "button", "background"],
  },
  {
    id: "border.header.button",
    label: "Border / Header Button",
    cssVar: "--header-button-border",
    category: "border",
    valueKind: "color",
    tags: ["header", "button", "border"],
  },
  {
    id: "surface.header.button-hover-bg",
    label: "Surface / Header Button Hover Background",
    cssVar: "--header-button-hover-bg",
    category: "surface",
    valueKind: "color",
    tags: ["header", "button", "hover", "background"],
  },
  {
    id: "border.header.button-hover",
    label: "Border / Header Button Hover",
    cssVar: "--header-button-hover-border",
    category: "border",
    valueKind: "color",
    tags: ["header", "button", "hover", "border"],
  },
  {
    id: "shadow.header.button-hover",
    label: "Shadow / Header Button Hover",
    cssVar: "--header-button-hover-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "button", "hover", "shadow"],
  },
  {
    id: "text.header.button-hover",
    label: "Text / Header Button Hover",
    cssVar: "--header-button-hover-text",
    category: "text",
    valueKind: "color",
    tags: ["header", "button", "hover", "text"],
  },
  {
    id: "shadow.header.button",
    label: "Shadow / Header Button",
    cssVar: "--header-button-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "button", "shadow"],
  },
  {
    id: "text.header.button",
    label: "Text / Header Button",
    cssVar: "--header-button-text",
    category: "text",
    valueKind: "color",
    tags: ["header", "button", "text"],
  },
  {
    id: "text.header.strong",
    label: "Text / Header Strong",
    cssVar: "--header-foreground-strong",
    category: "text",
    valueKind: "color",
    tags: ["header", "text"],
  },
  {
    id: "glass.header.top",
    label: "Glass / Header Top",
    cssVar: "--header-glass-top",
    category: "glass",
    valueKind: "color",
    tags: ["header", "glass"],
  },
  {
    id: "glass.header.bottom",
    label: "Glass / Header Bottom",
    cssVar: "--header-glass-bottom",
    category: "glass",
    valueKind: "color",
    tags: ["header", "glass"],
  },
  {
    id: "layout.header.height",
    label: "Layout / Header Height",
    cssVar: "--header-height",
    category: "layout",
    valueKind: "dimension",
    tags: ["header", "layout"],
  },
  {
    id: "border.header.launch",
    label: "Border / Header Launch",
    cssVar: "--header-launch-border",
    category: "border",
    valueKind: "color",
    tags: ["header", "launch", "border"],
  },
  {
    id: "shadow.header.launch",
    label: "Shadow / Header Launch",
    cssVar: "--header-launch-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "launch", "shadow"],
  },
  {
    id: "shadow.header.launch-active",
    label: "Shadow / Header Launch Active",
    cssVar: "--header-launch-shadow-active",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "launch", "shadow", "active"],
  },
  {
    id: "shadow.header.launch-hover",
    label: "Shadow / Header Launch Hover",
    cssVar: "--header-launch-shadow-hover",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "launch", "shadow", "hover"],
  },
  {
    id: "shadow.header.launch-text",
    label: "Shadow / Header Launch Text",
    cssVar: "--header-launch-text-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "launch", "text"],
  },
  {
    id: "surface.header.scrim",
    label: "Surface / Header Scrim",
    cssVar: "--header-scrim",
    category: "surface",
    valueKind: "color",
    tags: ["header", "scrim"],
  },
  {
    id: "shadow.header.base",
    label: "Shadow / Header Base",
    cssVar: "--header-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "shadow"],
  },
  {
    id: "brand.header.shadow-color",
    label: "Brand / Header Shadow Color",
    cssVar: "--header-shadow-color",
    category: "brand",
    valueKind: "color",
    tags: ["header", "shadow", "color"],
  },
  {
    id: "shadow.header.lg",
    label: "Shadow / Header LG",
    cssVar: "--header-shadow-lg",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "shadow", "lg"],
  },
  {
    id: "shadow.header.sm",
    label: "Shadow / Header SM",
    cssVar: "--header-shadow-sm",
    category: "shadow",
    valueKind: "shadow",
    tags: ["header", "shadow", "sm"],
  },
  {
    id: "brand.header.tint-from",
    label: "Brand / Header Tint From",
    cssVar: "--header-tint-from",
    category: "brand",
    valueKind: "color",
    tags: ["header", "tint"],
  },
  {
    id: "brand.header.tint-to",
    label: "Brand / Header Tint To",
    cssVar: "--header-tint-to",
    category: "brand",
    valueKind: "color",
    tags: ["header", "tint"],
  },
  {
    id: "brand.heading.from",
    label: "Brand / Heading From",
    cssVar: "--heading-from",
    category: "brand",
    valueKind: "color",
    tags: ["heading", "gradient"],
  },
  {
    id: "brand.heading.to",
    label: "Brand / Heading To",
    cssVar: "--heading-to",
    category: "brand",
    valueKind: "color",
    tags: ["heading", "gradient"],
  },
  {
    id: "utility.icon-plate.bg-1",
    label: "Utility / Icon Plate Background 1",
    cssVar: "--icon-plate-bg-1",
    category: "utility",
    valueKind: "color",
    tags: ["icon", "background"],
  },
  {
    id: "utility.icon-plate.bg-2",
    label: "Utility / Icon Plate Background 2",
    cssVar: "--icon-plate-bg-2",
    category: "utility",
    valueKind: "color",
    tags: ["icon", "background"],
  },
  {
    id: "utility.icon-plate.border",
    label: "Utility / Icon Plate Border",
    cssVar: "--icon-plate-border",
    category: "utility",
    valueKind: "color",
    tags: ["icon", "border"],
  },
  {
    id: "shadow.icon-plate.highlight",
    label: "Shadow / Icon Plate Highlight",
    cssVar: "--icon-plate-highlight",
    category: "shadow",
    valueKind: "shadow",
    tags: ["icon", "highlight"],
  },
  {
    id: "text.link",
    label: "Text / Link",
    cssVar: "--link-color",
    category: "text",
    valueKind: "color",
    tags: ["link", "text"],
  },
  {
    id: "utility.pill.bg-1",
    label: "Utility / Pill Background 1",
    cssVar: "--pill-bg-1",
    category: "utility",
    valueKind: "color",
    tags: ["pill", "background"],
  },
  {
    id: "utility.pill.bg-2",
    label: "Utility / Pill Background 2",
    cssVar: "--pill-bg-2",
    category: "utility",
    valueKind: "color",
    tags: ["pill", "background"],
  },
  {
    id: "utility.pill.border",
    label: "Utility / Pill Border",
    cssVar: "--pill-border",
    category: "utility",
    valueKind: "color",
    tags: ["pill", "border"],
  },
  {
    id: "surface.chip.bg-1",
    label: "Surface / Chip Background 1",
    cssVar: "--chip-bg-1",
    category: "surface",
    valueKind: "color",
    tags: ["chip", "background"],
  },
  {
    id: "surface.chip.bg-2",
    label: "Surface / Chip Background 2",
    cssVar: "--chip-bg-2",
    category: "surface",
    valueKind: "color",
    tags: ["chip", "background"],
  },
  {
    id: "border.chip",
    label: "Border / Chip",
    cssVar: "--chip-border",
    category: "border",
    valueKind: "color",
    tags: ["chip", "border"],
  },
  {
    id: "shadow.chip",
    label: "Shadow / Chip",
    cssVar: "--chip-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["chip", "shadow"],
  },
  {
    id: "surface.chip.hover-bg-1",
    label: "Surface / Chip Hover Background 1",
    cssVar: "--chip-hover-bg-1",
    category: "surface",
    valueKind: "color",
    tags: ["chip", "hover", "background"],
  },
  {
    id: "surface.chip.hover-bg-2",
    label: "Surface / Chip Hover Background 2",
    cssVar: "--chip-hover-bg-2",
    category: "surface",
    valueKind: "color",
    tags: ["chip", "hover", "background"],
  },
  {
    id: "border.chip.hover",
    label: "Border / Chip Hover",
    cssVar: "--chip-hover-border",
    category: "border",
    valueKind: "color",
    tags: ["chip", "hover", "border"],
  },
  {
    id: "shadow.chip.hover",
    label: "Shadow / Chip Hover",
    cssVar: "--chip-hover-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["chip", "hover", "shadow"],
  },
  {
    id: "surface.chip.active-bg-1",
    label: "Surface / Chip Active Background 1",
    cssVar: "--chip-active-bg-1",
    category: "surface",
    valueKind: "color",
    tags: ["chip", "active", "background"],
  },
  {
    id: "surface.chip.active-bg-2",
    label: "Surface / Chip Active Background 2",
    cssVar: "--chip-active-bg-2",
    category: "surface",
    valueKind: "color",
    tags: ["chip", "active", "background"],
  },
  {
    id: "border.chip.active",
    label: "Border / Chip Active",
    cssVar: "--chip-active-border",
    category: "border",
    valueKind: "color",
    tags: ["chip", "active", "border"],
  },
  {
    id: "shadow.chip.active",
    label: "Shadow / Chip Active",
    cssVar: "--chip-active-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["chip", "active", "shadow"],
  },
  {
    id: "radius.pill-custom",
    label: "Radius / Pill Custom",
    cssVar: "--pill-radius",
    category: "radius",
    valueKind: "radius",
    tags: ["pill", "radius"],
  },
  {
    id: "utility.prompt-glow.blur",
    label: "Utility / Prompt Glow Blur",
    cssVar: "--prompt-glow-blur",
    category: "utility",
    valueKind: "dimension",
    tags: ["prompt", "glow"],
  },
  {
    id: "utility.prompt-glow.opacity",
    label: "Utility / Prompt Glow Opacity",
    cssVar: "--prompt-glow-opacity",
    category: "utility",
    valueKind: "other",
    tags: ["prompt", "glow"],
  },
  {
    id: "surface.rail.bg-1",
    label: "Surface / Rail Background 1",
    cssVar: "--rail-bg-1",
    category: "surface",
    valueKind: "color",
    tags: ["rail", "background"],
  },
  {
    id: "surface.rail.bg-2",
    label: "Surface / Rail Background 2",
    cssVar: "--rail-bg-2",
    category: "surface",
    valueKind: "color",
    tags: ["rail", "background"],
  },
  {
    id: "surface.rail.border",
    label: "Surface / Rail Border",
    cssVar: "--rail-border",
    category: "surface",
    valueKind: "color",
    tags: ["rail", "border"],
  },
  {
    id: "surface.style.chats-badge-bg",
    label: "Surface Style / Chats Badge Background",
    cssVar: "--style-chats-badge-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "chats", "badge"],
  },
  {
    id: "surface.style.chats-badge-color",
    label: "Surface Style / Chats Badge Color",
    cssVar: "--style-chats-badge-color",
    category: "surface",
    valueKind: "color",
    tags: ["style", "chats", "badge"],
  },
  {
    id: "surface.style.chats-border-hover",
    label: "Surface Style / Chats Border Hover",
    cssVar: "--style-chats-border-hover",
    category: "surface",
    valueKind: "color",
    tags: ["style", "chats", "border", "hover"],
  },
  {
    id: "text.style.chats-desc",
    label: "Text Style / Chats Description",
    cssVar: "--style-chats-desc",
    category: "text",
    valueKind: "color",
    tags: ["style", "chats", "text"],
  },
  {
    id: "surface.style.chats-icon-color",
    label: "Surface Style / Chats Icon Color",
    cssVar: "--style-chats-icon-color",
    category: "surface",
    valueKind: "color",
    tags: ["style", "chats", "icon"],
  },
  {
    id: "shadow.style.chats",
    label: "Shadow Style / Chats",
    cssVar: "--style-chats-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["style", "chats", "shadow"],
  },
  {
    id: "shadow.style.chats-hover",
    label: "Shadow Style / Chats Hover",
    cssVar: "--style-chats-shadow-hover",
    category: "shadow",
    valueKind: "shadow",
    tags: ["style", "chats", "shadow", "hover"],
  },
  {
    id: "text.style.chats",
    label: "Text Style / Chats",
    cssVar: "--style-chats-text",
    category: "text",
    valueKind: "color",
    tags: ["style", "chats", "text"],
  },
  {
    id: "surface.style.friends-badge-bg",
    label: "Surface Style / Friends Badge Background",
    cssVar: "--style-friends-badge-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "friends", "badge"],
  },
  {
    id: "surface.style.friends-badge-color",
    label: "Surface Style / Friends Badge Color",
    cssVar: "--style-friends-badge-color",
    category: "surface",
    valueKind: "color",
    tags: ["style", "friends", "badge"],
  },
  {
    id: "surface.style.friends-border-hover",
    label: "Surface Style / Friends Border Hover",
    cssVar: "--style-friends-border-hover",
    category: "surface",
    valueKind: "color",
    tags: ["style", "friends", "border", "hover"],
  },
  {
    id: "text.style.friends-desc",
    label: "Text Style / Friends Description",
    cssVar: "--style-friends-desc",
    category: "text",
    valueKind: "color",
    tags: ["style", "friends", "text"],
  },
  {
    id: "surface.style.friends-icon-color",
    label: "Surface Style / Friends Icon Color",
    cssVar: "--style-friends-icon-color",
    category: "surface",
    valueKind: "color",
    tags: ["style", "friends", "icon"],
  },
  {
    id: "shadow.style.friends",
    label: "Shadow Style / Friends",
    cssVar: "--style-friends-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["style", "friends", "shadow"],
  },
  {
    id: "shadow.style.friends-hover",
    label: "Shadow Style / Friends Hover",
    cssVar: "--style-friends-shadow-hover",
    category: "shadow",
    valueKind: "shadow",
    tags: ["style", "friends", "shadow", "hover"],
  },
  {
    id: "text.style.friends",
    label: "Text Style / Friends",
    cssVar: "--style-friends-text",
    category: "text",
    valueKind: "color",
    tags: ["style", "friends", "text"],
  },
  {
    id: "surface.style.requests-badge-bg",
    label: "Surface Style / Requests Badge Background",
    cssVar: "--style-requests-badge-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "requests", "badge"],
  },
  {
    id: "surface.style.requests-badge-color",
    label: "Surface Style / Requests Badge Color",
    cssVar: "--style-requests-badge-color",
    category: "surface",
    valueKind: "color",
    tags: ["style", "requests", "badge"],
  },
  {
    id: "surface.style.requests-border-hover",
    label: "Surface Style / Requests Border Hover",
    cssVar: "--style-requests-border-hover",
    category: "surface",
    valueKind: "color",
    tags: ["style", "requests", "border", "hover"],
  },
  {
    id: "text.style.requests-desc",
    label: "Text Style / Requests Description",
    cssVar: "--style-requests-desc",
    category: "text",
    valueKind: "color",
    tags: ["style", "requests", "text"],
  },
  {
    id: "surface.style.requests-icon-color",
    label: "Surface Style / Requests Icon Color",
    cssVar: "--style-requests-icon-color",
    category: "surface",
    valueKind: "color",
    tags: ["style", "requests", "icon"],
  },
  {
    id: "shadow.style.requests",
    label: "Shadow Style / Requests",
    cssVar: "--style-requests-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["style", "requests", "shadow"],
  },
  {
    id: "shadow.style.requests-hover",
    label: "Shadow Style / Requests Hover",
    cssVar: "--style-requests-shadow-hover",
    category: "shadow",
    valueKind: "shadow",
    tags: ["style", "requests", "shadow", "hover"],
  },
  {
    id: "text.style.requests",
    label: "Text Style / Requests",
    cssVar: "--style-requests-text",
    category: "text",
    valueKind: "color",
    tags: ["style", "requests", "text"],
  },
  {
    id: "surface.friends.tabs-scrim",
    label: "Friends / Tabs Scrim",
    cssVar: "--friends-tabs-scrim",
    category: "surface",
    valueKind: "color",
    tags: ["friends", "tabs", "background"],
  },
  {
    id: "surface.friends.tab-background",
    label: "Friends / Tab Background",
    cssVar: "--friends-tab-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "tabs", "background", "gradient"],
  },
  {
    id: "surface.friends.badge-background",
    label: "Friends / Badge Background",
    cssVar: "--friends-badge-background",
    category: "surface",
    valueKind: "color",
    tags: ["friends", "badge", "background"],
  },
  {
    id: "text.friends.badge",
    label: "Friends / Badge Text",
    cssVar: "--friends-badge-text",
    category: "text",
    valueKind: "color",
    tags: ["friends", "badge", "text"],
  },
  {
    id: "text.friends.notice",
    label: "Friends / Notice Text",
    cssVar: "--friends-notice-text",
    category: "text",
    valueKind: "color",
    tags: ["friends", "notice", "text"],
  },
  {
    id: "surface.friends.empty-background",
    label: "Friends / Empty State Background",
    cssVar: "--friends-empty-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "empty", "background"],
  },
  {
    id: "surface.friends.retry-background",
    label: "Friends / Retry Background",
    cssVar: "--friends-retry-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "retry", "background"],
  },
  {
    id: "surface.friends.row-background",
    label: "Friends / Row Background",
    cssVar: "--friends-row-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "row", "background"],
  },
  {
    id: "shadow.friends.row",
    label: "Shadow / Friends Row",
    cssVar: "--friends-row-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["friends", "row", "shadow"],
  },
  {
    id: "surface.friends.avatar-background",
    label: "Friends / Avatar Background",
    cssVar: "--friends-avatar-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "avatar", "background"],
  },
  {
    id: "text.friends.avatar-fallback",
    label: "Friends / Avatar Fallback Text",
    cssVar: "--friends-avatar-fallback-text",
    category: "text",
    valueKind: "color",
    tags: ["friends", "avatar", "text"],
  },
  {
    id: "presence.friends.neutral",
    label: "Friends / Presence Neutral",
    cssVar: "--friends-presence-neutral-dot",
    category: "presence",
    valueKind: "color",
    tags: ["friends", "presence", "dot"],
  },
  {
    id: "presence.friends.neutral-muted",
    label: "Friends / Presence Neutral Muted",
    cssVar: "--friends-presence-neutral-dot-muted",
    category: "presence",
    valueKind: "color",
    tags: ["friends", "presence", "dot", "muted"],
  },
  {
    id: "surface.friends.menu-trigger-background",
    label: "Friends / Menu Trigger Background",
    cssVar: "--friends-menu-trigger-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "menu", "background"],
  },
  {
    id: "surface.friends.menu-panel-background",
    label: "Friends / Menu Panel Background",
    cssVar: "--friends-menu-panel-background",
    category: "surface",
    valueKind: "color",
    tags: ["friends", "menu", "background"],
  },
  {
    id: "shadow.friends.menu-panel",
    label: "Shadow / Friends Menu Panel",
    cssVar: "--friends-menu-panel-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["friends", "menu", "shadow"],
  },
  {
    id: "surface.friends.request-background",
    label: "Friends / Request Background",
    cssVar: "--friends-request-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "requests", "background"],
  },
  {
    id: "surface.friends.request-action-background",
    label: "Friends / Request Action Background",
    cssVar: "--friends-request-action-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "requests", "background", "action"],
  },
  {
    id: "surface.friends.request-primary-background",
    label: "Friends / Request Primary Background",
    cssVar: "--friends-request-primary-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "requests", "background", "primary"],
  },
  {
    id: "text.friends.party-action",
    label: "Friends / Party Action Text",
    cssVar: "--friends-party-action-text",
    category: "text",
    valueKind: "color",
    tags: ["friends", "party", "button", "text"],
  },
  {
    id: "surface.friends.party-action-background",
    label: "Friends / Party Action Background",
    cssVar: "--friends-party-action-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "party", "button", "background"],
  },
  {
    id: "border.friends.party-action",
    label: "Friends / Party Action Border",
    cssVar: "--friends-party-action-border",
    category: "border",
    valueKind: "color",
    tags: ["friends", "party", "button", "border"],
  },
  {
    id: "border.friends.party-action-hover",
    label: "Friends / Party Action Hover Border",
    cssVar: "--friends-party-action-hover-border",
    category: "border",
    valueKind: "color",
    tags: ["friends", "party", "button", "hover"],
  },
  {
    id: "border.friends.party-action-active",
    label: "Friends / Party Action Active Border",
    cssVar: "--friends-party-action-active-border",
    category: "border",
    valueKind: "color",
    tags: ["friends", "party", "button", "active"],
  },
  {
    id: "shadow.friends.party-action-active",
    label: "Shadow / Party Action Active",
    cssVar: "--friends-party-action-active-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["friends", "party", "button", "shadow"],
  },
  {
    id: "text.friends.group-action",
    label: "Friends / Group Action Text",
    cssVar: "--friends-group-action-text",
    category: "text",
    valueKind: "color",
    tags: ["friends", "group", "button", "text"],
  },
  {
    id: "surface.friends.group-action-background",
    label: "Friends / Group Action Background",
    cssVar: "--friends-group-action-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["friends", "group", "button", "background"],
  },
  {
    id: "border.friends.group-action",
    label: "Friends / Group Action Border",
    cssVar: "--friends-group-action-border",
    category: "border",
    valueKind: "color",
    tags: ["friends", "group", "button", "border"],
  },
  {
    id: "border.friends.group-action-hover",
    label: "Friends / Group Action Hover Border",
    cssVar: "--friends-group-action-hover-border",
    category: "border",
    valueKind: "color",
    tags: ["friends", "group", "button", "hover"],
  },
  {
    id: "border.friends.group-action-active",
    label: "Friends / Group Action Active Border",
    cssVar: "--friends-group-action-active-border",
    category: "border",
    valueKind: "color",
    tags: ["friends", "group", "button", "active"],
  },
  {
    id: "shadow.friends.group-action-active",
    label: "Shadow / Group Action Active",
    cssVar: "--friends-group-action-active-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["friends", "group", "button", "shadow"],
  },
  {
    id: "surface.prompter.ai-message-background",
    label: "Prompter / AI Message Background",
    cssVar: "--prompter-ai-message-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["prompter", "ai", "background", "gradient"],
  },
  {
    id: "text.prompter.ai-message",
    label: "Prompter / AI Message Text",
    cssVar: "--prompter-ai-message-text",
    category: "text",
    valueKind: "color",
    tags: ["prompter", "ai", "text"],
  },
  {
    id: "surface.prompter.primary-button-background",
    label: "Prompter / Primary Button Background",
    cssVar: "--prompter-primary-button-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["prompter", "button", "primary", "background", "gradient"],
  },
  {
    id: "text.prompter.primary-button",
    label: "Prompter / Primary Button Text",
    cssVar: "--prompter-primary-button-text",
    category: "text",
    valueKind: "color",
    tags: ["prompter", "button", "primary", "text"],
  },
  {
    id: "surface.chats.panel-background",
    label: "Chats / Panel Background",
    cssVar: "--chats-panel-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "panel", "background"],
  },
  {
    id: "shadow.chats.panel",
    label: "Shadow / Chats Panel",
    cssVar: "--chats-panel-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["chats", "panel", "shadow"],
  },
  {
    id: "surface.chats.empty-background",
    label: "Chats / Empty State Background",
    cssVar: "--chats-empty-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["chats", "empty", "background"],
  },
  {
    id: "surface.chats.thread-background",
    label: "Chats / Thread Background",
    cssVar: "--chats-thread-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["chats", "thread", "background"],
  },
  {
    id: "shadow.chats.thread-active",
    label: "Shadow / Chats Thread Active",
    cssVar: "--chats-thread-active-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["chats", "thread", "shadow"],
  },
  {
    id: "surface.chats.avatar-background",
    label: "Chats / Avatar Background",
    cssVar: "--chats-avatar-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "avatar", "background"],
  },
  {
    id: "surface.chats.thread-badge-background",
    label: "Chats / Thread Badge Background",
    cssVar: "--chats-thread-badge-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "thread", "badge", "background"],
  },
  {
    id: "text.chats.thread-badge",
    label: "Chats / Thread Badge Text",
    cssVar: "--chats-thread-badge-text",
    category: "text",
    valueKind: "color",
    tags: ["chats", "thread", "badge", "text"],
  },
  {
    id: "surface.chats.conversation-background",
    label: "Chats / Conversation Background",
    cssVar: "--chats-conversation-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["chats", "conversation", "background"],
  },
  {
    id: "surface.chats.control-background",
    label: "Chats / Control Background",
    cssVar: "--chats-control-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["chats", "control", "background"],
  },
  {
    id: "surface.chats.message-background",
    label: "Chats / Message Background",
    cssVar: "--chats-message-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "message", "background"],
  },
  {
    id: "shadow.chats.message",
    label: "Shadow / Chats Message",
    cssVar: "--chats-message-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["chats", "message", "shadow"],
  },
  {
    id: "surface.chats.message-self-background",
    label: "Chats / Message Self Background",
    cssVar: "--chats-message-self-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["chats", "message", "self", "background"],
  },
  {
    id: "text.chats.message-self",
    label: "Chats / Message Self Text",
    cssVar: "--chats-message-self-text",
    category: "text",
    valueKind: "color",
    tags: ["chats", "message", "self", "text"],
  },
  {
    id: "border.chats.error",
    label: "Chats / Error Border",
    cssVar: "--chats-error-border",
    category: "border",
    valueKind: "color",
    tags: ["chats", "error", "border"],
  },
  {
    id: "surface.chats.error-background",
    label: "Chats / Error Background",
    cssVar: "--chats-error-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "error", "background"],
  },
  {
    id: "text.chats.error",
    label: "Chats / Error Text",
    cssVar: "--chats-error-text",
    category: "text",
    valueKind: "color",
    tags: ["chats", "error", "text"],
  },
  {
    id: "surface.chats.composer-background",
    label: "Chats / Composer Background",
    cssVar: "--chats-composer-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "composer", "background"],
  },
  {
    id: "surface.composer.overlay",
    label: "Composer / Overlay Scrim",
    cssVar: "--composer-overlay",
    category: "surface",
    valueKind: "color",
    tags: ["composer", "overlay", "scrim"],
  },
  {
    id: "surface.composer.panel",
    label: "Composer / Panel Background",
    cssVar: "--composer-panel-background",
    category: "surface",
    valueKind: "color",
    tags: ["composer", "panel", "background"],
  },
  {
    id: "border.composer.panel",
    label: "Composer / Panel Border",
    cssVar: "--composer-panel-border",
    category: "border",
    valueKind: "color",
    tags: ["composer", "panel", "border"],
  },
  {
    id: "surface.composer.main",
    label: "Composer / Main Column Background",
    cssVar: "--composer-main-background",
    category: "surface",
    valueKind: "color",
    tags: ["composer", "main", "background"],
  },
  {
    id: "surface.composer.rail",
    label: "Composer / Rail Background",
    cssVar: "--composer-rail-background",
    category: "surface",
    valueKind: "color",
    tags: ["composer", "rail", "background"],
  },
  {
    id: "border.composer.rail",
    label: "Composer / Rail Border",
    cssVar: "--composer-rail-border",
    category: "border",
    valueKind: "color",
    tags: ["composer", "rail", "border"],
  },
  {
    id: "surface.composer.footer",
    label: "Composer / Footer Background",
    cssVar: "--composer-footer-background",
    category: "surface",
    valueKind: "color",
    tags: ["composer", "footer", "background"],
  },
  {
    id: "border.composer.footer",
    label: "Composer / Footer Border",
    cssVar: "--composer-footer-border",
    category: "border",
    valueKind: "color",
    tags: ["composer", "footer", "border"],
  },
  {
    id: "surface.composer.close",
    label: "Composer / Close Button Background",
    cssVar: "--composer-close-background",
    category: "surface",
    valueKind: "color",
    tags: ["composer", "close", "background"],
  },
  {
    id: "border.composer.close",
    label: "Composer / Close Button Border",
    cssVar: "--composer-close-border",
    category: "border",
    valueKind: "color",
    tags: ["composer", "close", "border"],
  },
  {
    id: "surface.composer.chat-user",
    label: "Composer / User Bubble Background",
    cssVar: "--composer-chat-user-background",
    category: "surface",
    valueKind: "color",
    tags: ["composer", "chat", "user"],
  },
  {
    id: "surface.composer.chat-ai",
    label: "Composer / AI Bubble Background",
    cssVar: "--composer-chat-ai-background",
    category: "surface",
    valueKind: "color",
    tags: ["composer", "chat", "ai"],
  },
  {
    id: "brand.composer.accent",
    label: "Composer / Accent",
    cssVar: "--composer-accent",
    category: "brand",
    valueKind: "color",
    tags: ["composer", "accent"],
  },
  {
    id: "brand.composer.accent-soft",
    label: "Composer / Accent Soft",
    cssVar: "--composer-accent-soft",
    category: "brand",
    valueKind: "color",
    tags: ["composer", "accent", "soft"],
  },
  {
    id: "feedback.composer.error",
    label: "Composer / Status Error",
    cssVar: "--composer-status-error",
    category: "feedback",
    valueKind: "color",
    tags: ["composer", "status", "error"],
  },
  {
    id: "feedback.composer.warning",
    label: "Composer / Status Warning",
    cssVar: "--composer-status-warning",
    category: "feedback",
    valueKind: "color",
    tags: ["composer", "status", "warning"],
  },
  {
    id: "feedback.composer.success",
    label: "Composer / Status Success",
    cssVar: "--composer-status-success",
    category: "feedback",
    valueKind: "color",
    tags: ["composer", "status", "success"],
  },
  {
    id: "border.chats.input",
    label: "Chats / Input Border",
    cssVar: "--chats-input-border",
    category: "border",
    valueKind: "color",
    tags: ["chats", "input", "border"],
  },
  {
    id: "surface.chats.input-background",
    label: "Chats / Input Background",
    cssVar: "--chats-input-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "input", "background"],
  },
  {
    id: "border.chats.send-button",
    label: "Chats / Send Button Border",
    cssVar: "--chats-send-button-border",
    category: "border",
    valueKind: "color",
    tags: ["chats", "button", "border"],
  },
  {
    id: "surface.chats.send-button-background",
    label: "Chats / Send Button Background",
    cssVar: "--chats-send-button-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["chats", "button", "background"],
  },
  {
    id: "text.chats.send-button",
    label: "Chats / Send Button Text",
    cssVar: "--chats-send-button-text",
    category: "text",
    valueKind: "color",
    tags: ["chats", "button", "text"],
  },
  {
    id: "surface.chats.reaction-background",
    label: "Chats / Reaction Background",
    cssVar: "--chats-reaction-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "reaction", "background"],
  },
  {
    id: "border.chats.reaction",
    label: "Chats / Reaction Border",
    cssVar: "--chats-reaction-border",
    category: "border",
    valueKind: "color",
    tags: ["chats", "reaction", "border"],
  },
  {
    id: "surface.chats.reaction-active-background",
    label: "Chats / Reaction Active Background",
    cssVar: "--chats-reaction-active-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "reaction", "active", "background"],
  },
  {
    id: "shadow.chats.reaction-active",
    label: "Shadow / Chats Reaction Active",
    cssVar: "--chats-reaction-active-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["chats", "reaction", "shadow", "active"],
  },
  {
    id: "surface.chats.reaction-add-background",
    label: "Chats / Reaction Add Background",
    cssVar: "--chats-reaction-add-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "reaction", "add", "background"],
  },
  {
    id: "border.chats.reaction-picker",
    label: "Chats / Reaction Picker Border",
    cssVar: "--chats-reaction-picker-border",
    category: "border",
    valueKind: "color",
    tags: ["chats", "reaction", "picker", "border"],
  },
  {
    id: "surface.chats.reaction-picker-background",
    label: "Chats / Reaction Picker Background",
    cssVar: "--chats-reaction-picker-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "reaction", "picker", "background"],
  },
  {
    id: "shadow.chats.reaction-picker",
    label: "Shadow / Chats Reaction Picker",
    cssVar: "--chats-reaction-picker-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["chats", "reaction", "picker", "shadow"],
  },
  {
    id: "surface.chats.menu-panel-background",
    label: "Chats / Menu Panel Background",
    cssVar: "--chats-menu-panel-background",
    category: "surface",
    valueKind: "color",
    tags: ["chats", "menu", "background"],
  },
  {
    id: "shadow.chats.menu-panel",
    label: "Shadow / Chats Menu Panel",
    cssVar: "--chats-menu-panel-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["chats", "menu", "shadow"],
  },
  {
    id: "surface.promo.short-background",
    label: "Promo / Short Background",
    cssVar: "--promo-short-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["promo", "short", "background"],
  },
  {
    id: "surface.promo.tile-hover-overlay",
    label: "Promo / Tile Hover Overlay",
    cssVar: "--promo-tile-hover-overlay",
    category: "surface",
    valueKind: "gradient",
    tags: ["promo", "tile", "overlay"],
  },
  {
    id: "surface.promo.overlay-gradient",
    label: "Promo / Media Overlay",
    cssVar: "--promo-overlay-gradient",
    category: "surface",
    valueKind: "gradient",
    tags: ["promo", "overlay", "background"],
  },
  {
    id: "surface.background-fx.purple",
    label: "Background FX / Purple",
    cssVar: "--background-fx-purple",
    category: "surface",
    valueKind: "gradient",
    tags: ["background", "fx", "purple"],
  },
  {
    id: "surface.background-fx.indigo",
    label: "Background FX / Indigo",
    cssVar: "--background-fx-indigo",
    category: "surface",
    valueKind: "gradient",
    tags: ["background", "fx", "indigo"],
  },
  {
    id: "surface.background-fx.pink",
    label: "Background FX / Pink",
    cssVar: "--background-fx-pink",
    category: "surface",
    valueKind: "gradient",
    tags: ["background", "fx", "pink"],
  },
  {
    id: "surface.background-fx.mist",
    label: "Background FX / Mist",
    cssVar: "--background-fx-mist",
    category: "surface",
    valueKind: "gradient",
    tags: ["background", "fx", "mist"],
  },
  {
    id: "surface.background-fx.stars",
    label: "Background FX / Stars",
    cssVar: "--background-fx-stars",
    category: "surface",
    valueKind: "gradient",
    tags: ["background", "fx", "stars", "night", "sparkle"],
  },
  {
    id: "surface.background-fx.snow",
    label: "Background FX / Snow",
    cssVar: "--background-fx-snow",
    category: "surface",
    valueKind: "gradient",
    tags: ["background", "fx", "snow", "winter", "flakes"],
  },
  {
    id: "surface.background-fx.confetti",
    label: "Background FX / Confetti",
    cssVar: "--background-fx-confetti",
    category: "surface",
    valueKind: "gradient",
    tags: ["background", "fx", "confetti", "celebration"],
  },
  {
    id: "surface.background-fx.scanlines",
    label: "Background FX / Scanlines",
    cssVar: "--background-fx-scanlines",
    category: "surface",
    valueKind: "gradient",
    tags: ["background", "fx", "scanlines", "retro"],
  },
  {
    id: "gradient.cta.launch-dark",
    label: "CTA / Launch Gradient Dark",
    cssVar: "--cta-gradient-launch-dark",
    category: "brand",
    valueKind: "gradient",
    tags: ["cta", "launch", "dark"],
  },
  {
    id: "shadow.cta.button",
    label: "CTA / Button Shadow",
    cssVar: "--cta-button-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["cta", "button", "shadow"],
  },
  {
    id: "surface.create.tile-background",
    label: "Create / Tile Background",
    cssVar: "--create-tile-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["create", "tile", "background"],
  },
  {
    id: "shadow.create.tile",
    label: "Shadow / Create Tile",
    cssVar: "--create-tile-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "tile", "shadow"],
  },
  {
    id: "surface.create.tile-hover-background",
    label: "Create / Tile Hover Background",
    cssVar: "--create-tile-hover-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["create", "tile", "hover", "background"],
  },
  {
    id: "shadow.create.tile-hover",
    label: "Shadow / Create Tile Hover",
    cssVar: "--create-tile-hover-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "tile", "hover", "shadow"],
  },
  {
    id: "shadow.create.tile-active",
    label: "Shadow / Create Tile Active",
    cssVar: "--create-tile-active-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "tile", "active", "shadow"],
  },
  {
    id: "surface.create.tile-expanded-background",
    label: "Create / Tile Expanded Background",
    cssVar: "--create-tile-expanded-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["create", "tile", "expanded", "background"],
  },
  {
    id: "shadow.create.tile-expanded",
    label: "Shadow / Create Tile Expanded",
    cssVar: "--create-tile-expanded-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "tile", "expanded", "shadow"],
  },
  {
    id: "shadow.create.back-button",
    label: "Shadow / Create Back Button",
    cssVar: "--create-back-button-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "button", "back", "shadow"],
  },
  {
    id: "surface.create.header-bottom-fade",
    label: "Create / Header Bottom Fade",
    cssVar: "--create-header-bottom-fade",
    category: "surface",
    valueKind: "gradient",
    tags: ["create", "header", "background"],
  },
  {
    id: "shadow.create.brand-mark",
    label: "Shadow / Create Brand Mark",
    cssVar: "--create-brand-mark-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "brand", "shadow"],
  },
  {
    id: "border.create.brand-mark",
    label: "Border / Create Brand Mark",
    cssVar: "--create-brand-mark-border",
    category: "border",
    valueKind: "color",
    tags: ["create", "brand", "border"],
  },
  {
    id: "surface.create.brand-name",
    label: "Create / Brand Name Gradient",
    cssVar: "--create-brand-name-gradient",
    category: "surface",
    valueKind: "gradient",
    tags: ["create", "brand", "text", "gradient"],
  },
  {
    id: "border.create.nav-link",
    label: "Border / Create Nav Link",
    cssVar: "--create-nav-link-border",
    category: "border",
    valueKind: "color",
    tags: ["create", "nav", "border"],
  },
  {
    id: "surface.create.nav-link-background",
    label: "Create / Nav Link Background",
    cssVar: "--create-nav-link-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["create", "nav", "background"],
  },
  {
    id: "shadow.create.nav-link",
    label: "Shadow / Create Nav Link",
    cssVar: "--create-nav-link-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "nav", "shadow"],
  },
  {
    id: "surface.create.nav-link-hover-background",
    label: "Create / Nav Link Hover Background",
    cssVar: "--create-nav-link-hover-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["create", "nav", "hover", "background"],
  },
  {
    id: "border.create.nav-link-hover",
    label: "Border / Create Nav Link Hover",
    cssVar: "--create-nav-link-hover-border",
    category: "border",
    valueKind: "color",
    tags: ["create", "nav", "hover", "border"],
  },
  {
    id: "shadow.create.nav-link-hover",
    label: "Shadow / Create Nav Link Hover",
    cssVar: "--create-nav-link-hover-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "nav", "hover", "shadow"],
  },
  {
    id: "surface.create.nav-link-active-background",
    label: "Create / Nav Link Active Background",
    cssVar: "--create-nav-link-active-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["create", "nav", "active", "background"],
  },
  {
    id: "border.create.nav-link-active",
    label: "Border / Create Nav Link Active",
    cssVar: "--create-nav-link-active-border",
    category: "border",
    valueKind: "color",
    tags: ["create", "nav", "active", "border"],
  },
  {
    id: "shadow.create.nav-link-active",
    label: "Shadow / Create Nav Link Active",
    cssVar: "--create-nav-link-active-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "nav", "active", "shadow"],
  },
  {
    id: "border.create.icon-button",
    label: "Border / Create Icon Button",
    cssVar: "--create-icon-button-border",
    category: "border",
    valueKind: "color",
    tags: ["create", "icon", "button", "border"],
  },
  {
    id: "shadow.create.icon-button",
    label: "Shadow / Create Icon Button",
    cssVar: "--create-icon-button-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["create", "icon", "button", "shadow"],
  },
  {
    id: "border.create.icon-button-hover",
    label: "Border / Create Icon Button Hover",
    cssVar: "--create-icon-button-hover-border",
    category: "border",
    valueKind: "color",
    tags: ["create", "icon", "button", "hover", "border"],
  },
  {
    id: "border.settings.nav-item",
    label: "Border / Settings Nav Item",
    cssVar: "--settings-nav-item-border",
    category: "border",
    valueKind: "color",
    tags: ["settings", "nav", "border"],
  },
  {
    id: "surface.settings.nav-item-background",
    label: "Settings / Nav Item Background",
    cssVar: "--settings-nav-item-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["settings", "nav", "background"],
  },
  {
    id: "shadow.settings.nav-item",
    label: "Shadow / Settings Nav Item",
    cssVar: "--settings-nav-item-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["settings", "nav", "shadow"],
  },
  {
    id: "shadow.settings.nav-item-active",
    label: "Shadow / Settings Nav Item Active",
    cssVar: "--settings-nav-item-active-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["settings", "nav", "active", "shadow"],
  },
  {
    id: "gradient.cta.launch-light",
    label: "CTA / Launch Gradient Light",
    cssVar: "--cta-gradient-launch-light",
    category: "brand",
    valueKind: "gradient",
    tags: ["cta", "launch", "light"],
  },
  {
    id: "surface.layer.1",
    label: "Surface / Layer 1",
    cssVar: "--surface-1",
    category: "surface",
    valueKind: "color",
    tags: ["surface", "layer"],
  },
  {
    id: "surface.layer.3",
    label: "Surface / Layer 3",
    cssVar: "--surface-3",
    category: "surface",
    valueKind: "color",
    tags: ["surface", "layer"],
  },
  {
    id: "surface.outline",
    label: "Surface / Outline",
    cssVar: "--surface-outline",
    category: "surface",
    valueKind: "color",
    tags: ["surface", "outline"],
  },
  {
    id: "text.legacy.primary",
    label: "Text / Legacy Primary",
    cssVar: "--text",
    category: "text",
    valueKind: "color",
    tags: ["legacy", "text"],
  },
  {
    id: "text.legacy.secondary",
    label: "Text / Legacy Secondary",
    cssVar: "--text-2",
    category: "text",
    valueKind: "color",
    tags: ["legacy", "text"],
  },
  {
    id: "text.legacy.tertiary",
    label: "Text / Legacy Tertiary",
    cssVar: "--text-3",
    category: "text",
    valueKind: "color",
    tags: ["legacy", "text"],
  },
  {
    id: "surface.tile.accent-a",
    label: "Surface / Tile Accent A",
    cssVar: "--tile-accent-a",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "accent"],
  },
  {
    id: "surface.tile.badge-bg-base",
    label: "Surface / Tile Badge Background Base",
    cssVar: "--tile-badge-bg-base",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "badge"],
  },
  {
    id: "surface.tile.badge-bg-final",
    label: "Surface / Tile Badge Background Final",
    cssVar: "--tile-badge-bg-final",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "badge"],
  },
  {
    id: "surface.tile.badge-color-base",
    label: "Surface / Tile Badge Color Base",
    cssVar: "--tile-badge-color-base",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "badge"],
  },
  {
    id: "surface.tile.badge-color-final",
    label: "Surface / Tile Badge Color Final",
    cssVar: "--tile-badge-color-final",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "badge"],
  },
  {
    id: "surface.tile.bg-base",
    label: "Surface / Tile Background Base",
    cssVar: "--tile-bg-base",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "background"],
  },
  {
    id: "surface.tile.bg-final",
    label: "Surface / Tile Background Final",
    cssVar: "--tile-bg-final",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "background"],
  },
  {
    id: "surface.tile.border-base",
    label: "Surface / Tile Border Base",
    cssVar: "--tile-border-base",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "border"],
  },
  {
    id: "surface.tile.border-final",
    label: "Surface / Tile Border Final",
    cssVar: "--tile-border-final",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "border"],
  },
  {
    id: "surface.tile.border-hover",
    label: "Surface / Tile Border Hover",
    cssVar: "--tile-border-hover",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "border", "hover"],
  },
  {
    id: "surface.tile.border-hover-base",
    label: "Surface / Tile Border Hover Base",
    cssVar: "--tile-border-hover-base",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "border", "hover"],
  },
  {
    id: "text.tile.desc-base",
    label: "Text / Tile Description Base",
    cssVar: "--tile-desc-base",
    category: "text",
    valueKind: "color",
    tags: ["tile", "description"],
  },
  {
    id: "text.tile.desc-final",
    label: "Text / Tile Description Final",
    cssVar: "--tile-desc-final",
    category: "text",
    valueKind: "color",
    tags: ["tile", "description"],
  },
  {
    id: "surface.tile.icon-bg-base",
    label: "Surface / Tile Icon Background Base",
    cssVar: "--tile-icon-bg-base",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "icon", "background"],
  },
  {
    id: "surface.tile.icon-bg-final",
    label: "Surface / Tile Icon Background Final",
    cssVar: "--tile-icon-bg-final",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "icon", "background"],
  },
  {
    id: "surface.tile.icon-color-base",
    label: "Surface / Tile Icon Color Base",
    cssVar: "--tile-icon-color-base",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "icon"],
  },
  {
    id: "surface.tile.icon-color-final",
    label: "Surface / Tile Icon Color Final",
    cssVar: "--tile-icon-color-final",
    category: "surface",
    valueKind: "color",
    tags: ["tile", "icon"],
  },
  {
    id: "shadow.tile.base",
    label: "Shadow / Tile Base",
    cssVar: "--tile-shadow-base",
    category: "shadow",
    valueKind: "shadow",
    tags: ["tile", "shadow"],
  },
  {
    id: "shadow.tile.final",
    label: "Shadow / Tile Final",
    cssVar: "--tile-shadow-final",
    category: "shadow",
    valueKind: "shadow",
    tags: ["tile", "shadow"],
  },
  {
    id: "shadow.tile.hover",
    label: "Shadow / Tile Hover",
    cssVar: "--tile-shadow-hover",
    category: "shadow",
    valueKind: "shadow",
    tags: ["tile", "shadow", "hover"],
  },
  {
    id: "shadow.tile.hover-base",
    label: "Shadow / Tile Hover Base",
    cssVar: "--tile-shadow-hover-base",
    category: "shadow",
    valueKind: "shadow",
    tags: ["tile", "shadow", "hover"],
  },
  {
    id: "text.tile.base",
    label: "Text / Tile Base",
    cssVar: "--tile-text-base",
    category: "text",
    valueKind: "color",
    tags: ["tile", "text"],
  },
  {
    id: "text.tile.final",
    label: "Text / Tile Final",
    cssVar: "--tile-text-final",
    category: "text",
    valueKind: "color",
    tags: ["tile", "text"],
  },

  {
    id: "surface.style.friends-bg",
    label: "Surface Style / Friends Background",
    cssVar: "--style-friends-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "friends", "background"],
  },
  {
    id: "surface.style.friends-border",
    label: "Surface Style / Friends Border",
    cssVar: "--style-friends-border",
    category: "surface",
    valueKind: "color",
    tags: ["style", "friends", "border"],
  },
  {
    id: "surface.style.friends-icon-bg",
    label: "Surface Style / Friends Icon Background",
    cssVar: "--style-friends-icon-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "friends", "icon"],
  },
  {
    id: "surface.style.chats-bg",
    label: "Surface Style / Chats Background",
    cssVar: "--style-chats-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "chats", "background"],
  },
  {
    id: "surface.style.chats-border",
    label: "Surface Style / Chats Border",
    cssVar: "--style-chats-border",
    category: "surface",
    valueKind: "color",
    tags: ["style", "chats", "border"],
  },
  {
    id: "surface.style.chats-icon-bg",
    label: "Surface Style / Chats Icon Background",
    cssVar: "--style-chats-icon-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "chats", "icon"],
  },
  {
    id: "surface.style.requests-bg",
    label: "Surface Style / Requests Background",
    cssVar: "--style-requests-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "requests", "background"],
  },
  {
    id: "surface.style.requests-border",
    label: "Surface Style / Requests Border",
    cssVar: "--style-requests-border",
    category: "surface",
    valueKind: "color",
    tags: ["style", "requests", "border"],
  },
  {
    id: "surface.style.requests-icon-bg",
    label: "Surface Style / Requests Icon Background",
    cssVar: "--style-requests-icon-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "requests", "icon"],
  },
  {
    id: "surface.party.hero-background",
    label: "Party / Hero Background",
    cssVar: "--party-hero-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["party", "hero", "background"],
  },
  {
    id: "surface.party.hero-accent",
    label: "Party / Hero Accent",
    cssVar: "--party-hero-accent",
    category: "surface",
    valueKind: "color",
    tags: ["party", "hero", "accent"],
  },
  {
    id: "surface.party.primary-background",
    label: "Party / Primary Button Background",
    cssVar: "--party-primary-background",
    category: "surface",
    valueKind: "gradient",
    tags: ["party", "button", "primary", "background"],
  },
  {
    id: "border.party.primary",
    label: "Party / Primary Button Border",
    cssVar: "--party-primary-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "button", "primary", "border"],
  },
  {
    id: "surface.party.status-background",
    label: "Party / Status Background",
    cssVar: "--party-status-background",
    category: "surface",
    valueKind: "color",
    tags: ["party", "status", "background"],
  },
  {
    id: "border.party.status",
    label: "Party / Status Border",
    cssVar: "--party-status-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "status", "border"],
  },
  {
    id: "border.party.startaudio",
    label: "Party / Start Audio Border",
    cssVar: "--party-startaudio-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "audio", "border"],
  },
  {
    id: "surface.party.startaudio-background",
    label: "Party / Start Audio Background",
    cssVar: "--party-startaudio-background",
    category: "surface",
    valueKind: "color",
    tags: ["party", "audio", "background"],
  },
  {
    id: "border.party.control-hover",
    label: "Party / Control Hover Border",
    cssVar: "--party-control-hover-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "control", "hover", "border"],
  },
  {
    id: "border.party.input-focus",
    label: "Party / Input Focus Border",
    cssVar: "--party-input-focus-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "input", "focus", "border"],
  },
  {
    id: "surface.party.panel-background",
    label: "Party / Panel Background",
    cssVar: "--party-panel-background",
    category: "surface",
    valueKind: "color",
    tags: ["party", "panel", "background"],
  },
  {
    id: "border.party.panel",
    label: "Party / Panel Border",
    cssVar: "--party-panel-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "panel", "border"],
  },
  {
    id: "surface.party.hero-actions-background",
    label: "Party / Hero Actions Background",
    cssVar: "--party-hero-actions-background",
    category: "surface",
    valueKind: "color",
    tags: ["party", "hero", "actions", "background"],
  },
  {
    id: "border.party.hero-actions",
    label: "Party / Hero Actions Border",
    cssVar: "--party-hero-actions-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "hero", "actions", "border"],
  },
  {
    id: "surface.party.input-background",
    label: "Party / Input Background",
    cssVar: "--party-input-background",
    category: "surface",
    valueKind: "color",
    tags: ["party", "input", "background"],
  },
  {
    id: "border.party.input",
    label: "Party / Input Border",
    cssVar: "--party-input-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "input", "border"],
  },
  {
    id: "surface.party.secondary-background",
    label: "Party / Secondary Button Background",
    cssVar: "--party-secondary-background",
    category: "surface",
    valueKind: "color",
    tags: ["party", "button", "secondary", "background"],
  },
  {
    id: "border.party.secondary",
    label: "Party / Secondary Button Border",
    cssVar: "--party-secondary-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "button", "secondary", "border"],
  },
  {
    id: "border.party.secondary-hover",
    label: "Party / Secondary Button Hover Border",
    cssVar: "--party-secondary-hover-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "button", "secondary", "hover", "border"],
  },
  {
    id: "surface.party.control-background",
    label: "Party / Control Background",
    cssVar: "--party-control-background",
    category: "surface",
    valueKind: "color",
    tags: ["party", "control", "background"],
  },
  {
    id: "surface.party.code-background",
    label: "Party / Code Background",
    cssVar: "--party-code-background",
    category: "surface",
    valueKind: "color",
    tags: ["party", "code", "background"],
  },
  {
    id: "border.party.code",
    label: "Party / Code Border",
    cssVar: "--party-code-border",
    category: "border",
    valueKind: "color",
    tags: ["party", "code", "border"],
  },
  {
    id: "surface.style.party-bg",
    label: "Surface Style / Party Background",
    cssVar: "--style-party-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "background"],
  },
  {
    id: "surface.style.party-border",
    label: "Surface Style / Party Border",
    cssVar: "--style-party-border",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "border"],
  },
  {
    id: "text.style.party",
    label: "Text Style / Party",
    cssVar: "--style-party-text",
    category: "text",
    valueKind: "color",
    tags: ["style", "party", "text"],
  },
  {
    id: "text.style.party-desc",
    label: "Text Style / Party Description",
    cssVar: "--style-party-desc",
    category: "text",
    valueKind: "color",
    tags: ["style", "party", "text"],
  },
  {
    id: "shadow.style.party",
    label: "Shadow Style / Party",
    cssVar: "--style-party-shadow",
    category: "shadow",
    valueKind: "shadow",
    tags: ["style", "party", "shadow"],
  },
  {
    id: "shadow.style.party-hover",
    label: "Shadow Style / Party Hover",
    cssVar: "--style-party-shadow-hover",
    category: "shadow",
    valueKind: "shadow",
    tags: ["style", "party", "shadow", "hover"],
  },
  {
    id: "surface.style.party-icon-bg",
    label: "Surface Style / Party Icon Background",
    cssVar: "--style-party-icon-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "icon"],
  },
  {
    id: "surface.style.party-icon-color",
    label: "Surface Style / Party Icon Color",
    cssVar: "--style-party-icon-color",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "icon"],
  },
  {
    id: "surface.style.party-badge-bg",
    label: "Surface Style / Party Badge Background",
    cssVar: "--style-party-badge-bg",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "badge"],
  },
  {
    id: "surface.style.party-badge-color",
    label: "Surface Style / Party Badge Color",
    cssVar: "--style-party-badge-color",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "badge"],
  },
  {
    id: "surface.style.party-border-hover",
    label: "Surface Style / Party Border Hover",
    cssVar: "--style-party-border-hover",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "border", "hover"],
  },
  {
    id: "surface.style.party-accent-a",
    label: "Surface Style / Party Accent A",
    cssVar: "--style-party-accent-a",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "accent"],
  },
  {
    id: "surface.style.party-accent-b",
    label: "Surface Style / Party Accent B",
    cssVar: "--style-party-accent-b",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "accent"],
  },
  {
    id: "surface.style.party-accent-c",
    label: "Surface Style / Party Accent C",
    cssVar: "--style-party-accent-c",
    category: "surface",
    valueKind: "color",
    tags: ["style", "party", "accent"],
  },
] as const satisfies readonly ThemeTokenDefinition[];

export type ThemeTokenId = (typeof themeTokenRegistry)[number]["id"];
export type ThemeTokenCssVar = (typeof themeTokenRegistry)[number]["cssVar"];

export type ThemeTokenMeta = {
  readonly id: ThemeTokenId;
  readonly cssVar: ThemeTokenCssVar;
  readonly category: ThemeTokenCategory;
  readonly valueKind: ThemeTokenValueKind;
  readonly label: string;
  readonly tags: readonly string[];
};

const THEME_TOKEN_META_ENTRIES = themeTokenRegistry.map(
  (token) =>
    [
      token.cssVar,
      {
        id: token.id as ThemeTokenId,
        cssVar: token.cssVar as ThemeTokenCssVar,
        category: token.category,
        valueKind: token.valueKind,
        label: token.label,
        tags: token.tags ?? [],
      },
    ] as const,
);

export const themeTokenMetaByCssVar = Object.freeze(
  Object.fromEntries(THEME_TOKEN_META_ENTRIES),
) as unknown as Record<ThemeTokenCssVar, ThemeTokenMeta>;
export const themeTokensById: ReadonlyMap<ThemeTokenId, ThemeTokenDefinition> = new Map(
  themeTokenRegistry.map((token) => [token.id as ThemeTokenId, token]),
);

export const themeTokensByCssVar: ReadonlyMap<ThemeTokenCssVar, ThemeTokenDefinition> = new Map(
  themeTokenRegistry.map((token) => [token.cssVar as ThemeTokenCssVar, token]),
);

export const THEME_TOKEN_CSS_VARS = new Set<ThemeTokenCssVar>(
  themeTokenRegistry.map((token) => token.cssVar),
);

export type TailwindThemeExtension = Partial<Record<TailwindGroup, Record<string, unknown>>>;

export function buildTailwindThemeExtension(
  tokens: readonly ThemeTokenDefinition[] = themeTokenRegistry,
): TailwindThemeExtension {
  const extend: TailwindThemeExtension = {};
  for (const token of tokens) {
    const binding = token.tailwind;
    if (!binding) continue;
    const [group, ...path] = binding.path;
    if (!path.length) continue;
    const base = (extend[group] ??= {});
    let cursor: Record<string, unknown> = base;
    for (let i = 0; i < path.length - 1; i++) {
      const key = path[i]!;
      const next = cursor[key];
      if (typeof next === "object" && next !== null) {
        cursor = next as Record<string, unknown>;
      } else {
        const fresh: Record<string, unknown> = {};
        cursor[key] = fresh;
        cursor = fresh;
      }
    }
    const leafKey = path[path.length - 1]!;
    cursor[leafKey] = `var(${token.cssVar})`;
  }
  return extend;
}

export function isThemeTokenVar(input: string): input is ThemeTokenCssVar {
  return THEME_TOKEN_CSS_VARS.has(input as ThemeTokenCssVar);
}

export function asCssVar(value: ThemeTokenCssVar): string {
  return `var(${value})`;
}

export const tailwindThemeExtension = buildTailwindThemeExtension();

const CORE_THEME_CATEGORIES: readonly ThemeTokenCategory[] = [
  "surface",
  "text",
  "border",
  "brand",
  "card",
  "dock",
  "glass",
  "ring",
  "feedback",
  "presence",
  "shadow",
  "layout",
  "utility",
  "motion",
] as const;

const CONTEXTUAL_TOKEN_PREFIXES: readonly string[] = [
  "home.",
  "friends.",
  "chats.",
  "requests.",
  "party.",
  "prompter.",
  "surface.style.",
  "text.style.",
  "shadow.style.",
  "border.style.",
  "surface.friends.",
  "text.friends.",
  "border.friends.",
  "shadow.friends.",
  "surface.chats.",
  "text.chats.",
  "border.chats.",
  "shadow.chats.",
  "surface.party.",
  "text.party.",
  "border.party.",
  "shadow.party.",
  "surface.create.",
  "text.create.",
  "border.create.",
  "shadow.create.",
  "surface.settings.",
  "text.settings.",
  "border.settings.",
  "shadow.settings.",
  "surface.tile.",
  "text.tile.",
  "border.tile.",
  "shadow.tile.",
] as const;

const isContextualToken = (token: ThemeTokenDefinition): boolean =>
  CONTEXTUAL_TOKEN_PREFIXES.some((prefix) => token.id.startsWith(prefix));

export const coreSiteThemeTokens = themeTokenRegistry.filter(
  (token) => CORE_THEME_CATEGORIES.includes(token.category) && !isContextualToken(token),
);

export const CORE_SITE_THEME_TOKEN_IDS = coreSiteThemeTokens.map(
  (token) => token.id as ThemeTokenId,
);

export const CORE_SITE_THEME_TOKEN_SET = new Set<ThemeTokenId>(CORE_SITE_THEME_TOKEN_IDS);

export const CORE_SITE_THEME_TOKEN_CSS_VARS = new Set<ThemeTokenCssVar>(
  coreSiteThemeTokens.map((token) => token.cssVar as ThemeTokenCssVar),
);
