create table if not exists public.user_panel_layouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  view text not null,
  storage_key text not null,
  state jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists user_panel_layouts_user_storage_idx
  on public.user_panel_layouts (user_id, storage_key);
create index if not exists user_panel_layouts_user_view_idx
  on public.user_panel_layouts (user_id, view);
drop trigger if exists user_panel_layouts_set_updated_at on public.user_panel_layouts;
create trigger user_panel_layouts_set_updated_at
  before update on public.user_panel_layouts
  for each row
  execute function public.set_updated_at();
