import { z } from "zod";

import { NOTIFICATION_TYPES } from "@/shared/notifications";

export const notificationTypeSchema = z.enum(NOTIFICATION_TYPES);

export const notificationSettingsSchema = z.object({
  commentOnPost: z.boolean(),
  commentOnPostEmail: z.boolean(),
  commentReply: z.boolean(),
  commentReplyEmail: z.boolean(),
  mention: z.boolean(),
  mentionEmail: z.boolean(),
  postLike: z.boolean(),
  postLikeEmail: z.boolean(),
  capsuleNewPost: z.boolean(),
  capsuleNewPostEmail: z.boolean(),
  friendRequest: z.boolean(),
  friendRequestEmail: z.boolean(),
  friendRequestAccepted: z.boolean(),
  friendRequestAcceptedEmail: z.boolean(),
  capsuleInvite: z.boolean(),
  capsuleInviteEmail: z.boolean(),
  capsuleInviteAccepted: z.boolean(),
  capsuleInviteAcceptedEmail: z.boolean(),
  capsuleInviteDeclined: z.boolean(),
  capsuleInviteDeclinedEmail: z.boolean(),
  capsuleRequestPending: z.boolean(),
  capsuleRequestPendingEmail: z.boolean(),
  capsuleRequestApproved: z.boolean(),
  capsuleRequestApprovedEmail: z.boolean(),
  capsuleRequestDeclined: z.boolean(),
  capsuleRequestDeclinedEmail: z.boolean(),
  capsuleRoleChanged: z.boolean(),
  capsuleRoleChangedEmail: z.boolean(),
  ladderChallenge: z.boolean(),
  ladderChallengeEmail: z.boolean(),
  ladderChallengeResolved: z.boolean(),
  ladderChallengeResolvedEmail: z.boolean(),
  directMessage: z.boolean(),
  directMessageEmail: z.boolean(),
  groupMessage: z.boolean(),
  groupMessageEmail: z.boolean(),
  followNew: z.boolean(),
  followNewEmail: z.boolean(),
  ladderMatchScheduled: z.boolean(),
  ladderMatchScheduledEmail: z.boolean(),
  ladderInvitedToJoin: z.boolean(),
  ladderInvitedToJoinEmail: z.boolean(),
  partyInvite: z.boolean(),
  partyInviteEmail: z.boolean(),
  partyInviteAccepted: z.boolean(),
  partyInviteAcceptedEmail: z.boolean(),
  mentionInChat: z.boolean(),
  mentionInChatEmail: z.boolean(),
  liveEventStarting: z.boolean(),
  liveEventStartingEmail: z.boolean(),
  streamStatus: z.boolean(),
  streamStatusEmail: z.boolean(),
  billingIssues: z.boolean(),
  billingIssuesEmail: z.boolean(),
  billingUpdates: z.boolean(),
  billingUpdatesEmail: z.boolean(),
  capsuleSupportSent: z.boolean(),
  capsuleSupportSentEmail: z.boolean(),
  capsuleSupportReceived: z.boolean(),
  capsuleSupportReceivedEmail: z.boolean(),
  storeOrders: z.boolean(),
  storeOrdersEmail: z.boolean(),
  storeSales: z.boolean(),
  storeSalesEmail: z.boolean(),
  emailDigestFrequency: z.enum(["instant", "daily", "weekly", "off"]),
});

export const notificationSchema = z.object({
  id: z.string(),
  type: notificationTypeSchema,
  title: z.string(),
  body: z.string().nullable(),
  href: z.string().nullable(),
  data: z.record(z.string(), z.unknown()).nullable(),
  createdAt: z.string(),
  readAt: z.string().nullable(),
});

export const notificationListResponseSchema = z.object({
  notifications: z.array(notificationSchema),
  unreadCount: z.number(),
});
